# Generated by Django 5.2.16 on 2026-08-25 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


# W2 wydzielenia Kontroli HU: przejęcie ISTNIEJĄCYCH tabel ui_* (db_table w modelach)
# — wyłącznie zmiana stanu, zero SQL (SeparateDatabaseAndState).
class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ui', '0186_remove_pickeractivity_batch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=[
        migrations.CreateModel(
            name='ControlledWarehouseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=40, unique=True, verbose_name='Typ magazynu')),
            ],
            options={
                'verbose_name': 'Kontrolowany typ magazynu',
                'verbose_name_plural': 'Kontrolowane typy magazynu',
                'db_table': 'ui_controlledwarehousetype',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='HUPrintProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Projekt')),
                ('label_text', models.CharField(blank=True, default='', help_text='Duży tekst na etykiecie; puste = tylko numer (np. Projekt Alfa).', max_length=40, verbose_name='Nazwa na etykiecie')),
                ('next_number', models.BigIntegerField(default=1, help_text='Kolejny numer do wydruku (edytowalny start).', verbose_name='Następny numer')),
                ('digits', models.PositiveSmallIntegerField(default=9, verbose_name='Liczba cyfr (zero-padding)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Projekt wydruku HU',
                'verbose_name_plural': 'Projekty wydruku HU',
                'db_table': 'ui_huprintproject',
                'ordering': ['next_number', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EscalationRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_type', models.CharField(blank=True, default='', max_length=40, unique=True, verbose_name='Typ magazynu (pusty = globalna)')),
                ('escalate_after_minutes', models.PositiveSmallIntegerField(default=0, help_text='0 = kierownik zmiany od razu; >0 = dopiero gdy brak reakcji po tym czasie.', verbose_name='Eskaluj do kierownika po [min]')),
                ('area_leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalation_area', to=settings.AUTH_USER_MODEL, verbose_name='Lider obszaru')),
                ('picking_leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalation_picking', to=settings.AUTH_USER_MODEL, verbose_name='Lider pickingu')),
                ('shift_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalation_shift', to=settings.AUTH_USER_MODEL, verbose_name='Kierownik zmiany')),
            ],
            options={
                'verbose_name': 'Ścieżka eskalacji',
                'verbose_name_plural': 'Ścieżki eskalacji',
                'db_table': 'ui_escalationroute',
                'ordering': ['warehouse_type'],
            },
        ),
        migrations.CreateModel(
            name='HandlingUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField(default=1, verbose_name='Nr palety')),
                ('code', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='pickHU')),
                ('status', models.CharField(choices=[('planned', 'Zaplanowany'), ('in_control', 'W kontroli'), ('ok', 'Zgodny'), ('to_recheck', 'Do rekontroli'), ('escaped', 'Wyjechało bez kontroli')], default='planned', max_length=12, verbose_name='Status')),
                ('location', models.CharField(blank=True, max_length=40, verbose_name='Lokalizacja')),
                ('recipient_type', models.CharField(blank=True, max_length=40, verbose_name='Typ odbiorcy')),
                ('warehouse_type', models.CharField(blank=True, max_length=40, verbose_name='Typ magazynu')),
                ('picker', models.CharField(blank=True, db_index=True, max_length=80, verbose_name='Picker (kompletujący)')),
                ('called_at', models.DateTimeField(blank=True, null=True, verbose_name='Wywołana o')),
                ('snooze_until', models.DateTimeField(blank=True, null=True, verbose_name='Odłożona do')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_priority', models.BooleanField(db_index=True, default=False, verbose_name='Priorytet (rekontrola)')),
                ('client_reqs_confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Wymagania klienta potwierdzone')),
                ('short_dated_ack_at', models.DateTimeField(blank=True, null=True, verbose_name='Krótki termin potwierdzony')),
                ('is_completed', models.BooleanField(db_index=True, default=False, verbose_name='Skompletowana (picking)')),
                ('stock_status', models.CharField(blank=True, default='', max_length=12, verbose_name='Status zapasu (SAP)')),
                ('weight_kg', models.FloatField(blank=True, null=True, verbose_name='Waga [kg]')),
                ('length_cm', models.FloatField(blank=True, null=True, verbose_name='Długość [cm]')),
                ('width_cm', models.FloatField(blank=True, null=True, verbose_name='Szerokość [cm]')),
                ('height_cm', models.FloatField(blank=True, null=True, verbose_name='Wysokość [cm]')),
                ('control_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_hus', to=settings.AUTH_USER_MODEL, verbose_name='Przydzielona do')),
                ('client_reqs_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hu_reqs_confirmed', to=settings.AUTH_USER_MODEL)),
                ('controlled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controlled_hus', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handling_units', to='ui.shipment')),
                ('short_dated_ack_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hu_short_dated_ack', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ui_handlingunit',
                'ordering': ['shipment', 'seq'],
            },
        ),
        migrations.CreateModel(
            name='GlsPackingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartons', models.PositiveSmallIntegerField(verbose_name='Kartony w przygotowaniu')),
                ('parcels', models.PositiveSmallIntegerField(verbose_name='Zrobione paczki')),
                ('volume_m3', models.FloatField(blank=True, null=True, verbose_name='Objętość palety [m³]')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('controller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gls_packing_entries', to=settings.AUTH_USER_MODEL)),
                ('hu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gls_packing', to='huctl.handlingunit')),
            ],
            options={
                'verbose_name': 'Rozliczenie pakowania GLS',
                'verbose_name_plural': 'Rozliczenia pakowania GLS',
                'db_table': 'ui_glspackingentry',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HandlingUnitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_code', models.CharField(max_length=50, verbose_name='Kod / REF')),
                ('description', models.CharField(blank=True, max_length=120, verbose_name='Opis')),
                ('lot', models.CharField(blank=True, max_length=16, verbose_name='LOT producenta')),
                ('expiry', models.DateField(blank=True, null=True, verbose_name='Data ważności')),
                ('vendor_batch', models.CharField(blank=True, max_length=40, verbose_name='Partia producenta')),
                ('mfg_date', models.DateField(blank=True, null=True, verbose_name='Data produkcji')),
                ('base_unit', models.CharField(blank=True, max_length=20, verbose_name='Jedn. podstawowa (JP)')),
                ('base_qty', models.FloatField(default=0, verbose_name='Ilość JP')),
                ('alt_unit', models.CharField(default='KAR', max_length=20, verbose_name='Jedn. alternatywna (AJM)')),
                ('alt_qty', models.FloatField(default=0, verbose_name='Ilość AJM')),
                ('expected_qty', models.FloatField(default=0, verbose_name='Oczekiwana ilość')),
                ('unit', models.CharField(default='kar', max_length=20, verbose_name='Jednostka')),
                ('weight_kg', models.FloatField(blank=True, null=True, verbose_name='Waga [kg]')),
                ('md_exception', models.BooleanField(default=False, verbose_name='Wyjątek master daty')),
                ('md_exception_note', models.CharField(blank=True, max_length=200, verbose_name='Opis niezgodności master daty')),
                ('controlled', models.BooleanField(default=False, verbose_name='Skontrolowano')),
                ('counted_qty', models.FloatField(blank=True, null=True, verbose_name='Zliczono')),
                ('counted_unit', models.CharField(blank=True, max_length=20)),
                ('result', models.CharField(choices=[('', '—'), ('ok', 'Potwierdzony'), ('error', 'Błąd')], default='', max_length=8, verbose_name='Wynik')),
                ('error_flags', models.JSONField(blank=True, default=dict, verbose_name='Flagi błędów')),
                ('vendor_batch_ok', models.BooleanField(default=False, verbose_name='Partia potwierdzona')),
                ('expiry_ok', models.BooleanField(default=False, verbose_name='Data ważności potwierdzona')),
                ('controlled_at', models.DateTimeField(blank=True, null=True)),
                ('hu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='huctl.handlingunit')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ui.product')),
            ],
            options={
                'db_table': 'ui_handlingunititem',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HUControlAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_recheck', models.BooleanField(default=False)),
                ('counted_qty', models.FloatField(blank=True, null=True)),
                ('counted_unit', models.CharField(blank=True, max_length=20)),
                ('exp_base_qty', models.FloatField(default=0)),
                ('exp_base_unit', models.CharField(blank=True, max_length=20)),
                ('exp_alt_qty', models.FloatField(default=0)),
                ('exp_alt_unit', models.CharField(blank=True, max_length=20)),
                ('result', models.CharField(blank=True, max_length=8)),
                ('error_flags', models.JSONField(blank=True, default=dict)),
                ('seconds_since_prev', models.FloatField(blank=True, null=True, verbose_name='Czas od poprzedniej pozycji [s]')),
                ('client_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('input_source', models.CharField(blank=True, default='', max_length=12, verbose_name='Źródło inputu')),
                ('device_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('controller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hu_attempts', to=settings.AUTH_USER_MODEL)),
                ('hu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_attempts', to='huctl.handlingunit')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_attempts', to='huctl.handlingunititem')),
            ],
            options={
                'db_table': 'ui_hucontrolattempt',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HUControlPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='hu_control/%Y/%m/', verbose_name='Zdjęcie')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('hu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_photos', to='huctl.handlingunit')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kontroler')),
            ],
            options={
                'verbose_name': 'Zdjęcie kontroli HU',
                'verbose_name_plural': 'Zdjęcia kontroli HU',
                'db_table': 'ui_hucontrolphoto',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HUPrintRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=150, verbose_name='Użytkownik')),
                ('quantity', models.PositiveIntegerField(verbose_name='Ilość etykiet')),
                ('from_number', models.BigIntegerField(verbose_name='Od numeru')),
                ('to_number', models.BigIntegerField(verbose_name='Do numeru')),
                ('symbology', models.CharField(default='code128', max_length=10, verbose_name='Symbolika')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='huctl.huprintproject')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hu_print_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Przebieg wydruku HU',
                'verbose_name_plural': 'Przebiegi wydruku HU',
                'db_table': 'ui_huprintrun',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HUQualityIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('wrong_assortment', 'Błędny asortyment / zły indeks'), ('damaged', 'Uszkodzony towar'), ('wrong_batch', 'Błędna seria'), ('ajm_conversion', 'Błąd przelicznika AJM'), ('wrong_expiry', 'Błędna data ważności'), ('bad_placement', 'Nieprawidłowe ułożenie'), ('wrong_label', 'Błąd na etykiecie'), ('missing_document', 'Brak dokumentu / certyfikatu'), ('foreign_item', 'Obcy / nadmiarowy towar')], max_length=24, verbose_name='Typ')),
                ('ref_code', models.CharField(blank=True, max_length=50, verbose_name='REF (obcy towar)')),
                ('qty', models.FloatField(blank=True, null=True, verbose_name='Ilość')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='Opis')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='quality/%Y/%m/', verbose_name='Zdjęcie')),
                ('status', models.CharField(choices=[('open', 'Otwarte'), ('closed', 'Zamknięte')], default='open', max_length=8)),
                ('resolution_note', models.CharField(blank=True, max_length=300, verbose_name='Rozwiązanie')),
                ('raised_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_quality_issues', to=settings.AUTH_USER_MODEL)),
                ('hu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_issues', to='huctl.handlingunit')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quality_issues', to='huctl.handlingunititem')),
                ('raised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raised_quality_issues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ui_huqualityissue',
                'ordering': ['-raised_at'],
            },
        ),
        migrations.CreateModel(
            name='HUStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('status', 'zmiana statusu'), ('call', 'wywołanie'), ('release', 'zwolnienie')], db_index=True, default='status', max_length=8)),
                ('from_status', models.CharField(blank=True, choices=[('planned', 'Zaplanowany'), ('in_control', 'W kontroli'), ('ok', 'Zgodny'), ('to_recheck', 'Do rekontroli'), ('escaped', 'Wyjechało bez kontroli')], max_length=12)),
                ('to_status', models.CharField(choices=[('planned', 'Zaplanowany'), ('in_control', 'W kontroli'), ('ok', 'Zgodny'), ('to_recheck', 'Do rekontroli'), ('escaped', 'Wyjechało bez kontroli')], max_length=12)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hu_status_events', to=settings.AUTH_USER_MODEL)),
                ('hu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='huctl.handlingunit')),
            ],
            options={
                'verbose_name': 'Zdarzenie statusu HU',
                'verbose_name_plural': 'Zdarzenia statusu HU',
                'db_table': 'ui_hustatusevent',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ControllerZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=40, verbose_name='Typ magazynu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_zones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Strefa kontroli użytkownika',
                'verbose_name_plural': 'Strefy kontroli (użytkownik × typ magazynu)',
                'db_table': 'ui_controllerzone',
                'ordering': ['user_id', 'code'],
                'unique_together': {('user', 'code')},
            },
        ),
        migrations.AddConstraint(
            model_name='handlingunit',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'ok'), _negated=True), ('verified_at__isnull', False), _connector='OR'), name='hu_ok_requires_verified_at'),
        ),
        migrations.AddConstraint(
            model_name='handlingunit',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('code',), name='hu_code_uniq'),
        ),
        migrations.AlterUniqueTogether(
            name='handlingunit',
            unique_together={('shipment', 'seq')},
        ),
        migrations.AddConstraint(
            model_name='hucontrolattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('client_id', ''), _negated=True), fields=('client_id',), name='huattempt_client_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='huqualityissue',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('hu', 'item', 'issue_type'), name='huqi_open_dedup'),
        ),
        ]),
    ]
