# Generated by Django 5.2.16 on 2026-08-25 20:07

import django.db.models.deletion
from django.db import migrations, models


# W2 Transportu: FK HandlingUnit.shipment wskazuje transport.Shipment (ta sama tabela/kolumna)
# — wyłącznie zmiana stanu, zero SQL (SeparateDatabaseAndState).
class Migration(migrations.Migration):

    dependencies = [
        ('huctl', '0001_initial'),
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=[
        migrations.AlterField(
            model_name='handlingunit',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handling_units', to='transport.shipment'),
        ),
        ]),
    ]
