# Generated by Django 5.2.16 on 2026-09-03 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huctl', '0002_alter_handlingunit_shipment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HUErrorInvestigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(choices=[('missing', 'Brak sztuk'), ('excess', 'Nadmiar'), ('wrong_batch', 'Zła partia'), ('wrong_expiry', 'Błąd daty ważności'), ('bad_placement', 'Błędne ułożenie')], max_length=20, verbose_name='Typ błędu')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='Notatka')),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('rejected', models.BooleanField(default=False)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_investigations', to=settings.AUTH_USER_MODEL)),
                ('controller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hu_investigations', to=settings.AUTH_USER_MODEL)),
                ('hu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigations', to='huctl.handlingunit')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigations', to='huctl.handlingunititem')),
            ],
            options={
                'verbose_name': 'Wyjaśnianie błędu HU',
                'verbose_name_plural': 'Wyjaśniania błędów HU',
                'ordering': ['-started_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('hu',), name='one_open_investigation_per_hu')],
            },
        ),
    ]
