# Generated by Django 5.2.16 on 2026-09-28 00:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huctl', '0003_huerrorinvestigation'),
        ('transport', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='handlingunit',
            index=models.Index(fields=['status', 'warehouse_type'], name='hu_status_whtype_idx'),
        ),
    ]
