# Generated by Django 6.0.2 on 2026-02-05 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=250)),
                ('pallet_code', models.CharField(default='Z129', max_length=20)),
                ('pallet_length_cm', models.IntegerField(default=129)),
                ('pallet_width_cm', models.IntegerField(default=80)),
                ('max_height_total_cm', models.IntegerField(default=215)),
                ('pallet_base_height_cm', models.IntegerField(default=15)),
                ('max_weight_kg', models.IntegerField(default=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Palletization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sku', models.CharField(max_length=80)),
                ('variant', models.CharField(default='STD', max_length=80)),
                ('carton_l', models.IntegerField()),
                ('carton_w', models.IntegerField()),
                ('carton_h', models.IntegerField()),
                ('unit_weight', models.FloatField()),
                ('pcs_per_carton', models.IntegerField()),
                ('demand_pcs', models.IntegerField()),
                ('carton_tare', models.FloatField(default=0.0)),
                ('layouts', models.JSONField(default=list)),
                ('selected_layout', models.CharField(blank=True, max_length=120)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ui.batch')),
            ],
        ),
    ]
