# Generated by Django 5.2.14 on 2026-05-08 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Carton",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=250, verbose_name="Nazwa opakowania"),
                ),
                (
                    "ean",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="EAN opakowania"
                    ),
                ),
                ("length_cm", models.IntegerField(verbose_name="L [cm]")),
                ("width_cm", models.IntegerField(verbose_name="W [cm]")),
                ("height_cm", models.IntegerField(verbose_name="H [cm]")),
                ("unit_weight_kg", models.FloatField(verbose_name="Waga jedn. [kg]")),
                (
                    "pieces_per_carton",
                    models.IntegerField(default=1, verbose_name="Szt / karton"),
                ),
                (
                    "tare_kg",
                    models.FloatField(default=0.0, verbose_name="Tara kartonu [kg]"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Uwagi")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktywny"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Karton",
                "verbose_name_plural": "Kartony",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        unique=True,
                        verbose_name="Kod indeksu",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="Nazwa")),
                ("description", models.TextField(blank=True, verbose_name="Opis")),
                (
                    "ean",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="EAN / barcode"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktywny"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Produkt",
                "verbose_name_plural": "Produkty",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="PalletizationInstruction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="Wersja"),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="Nazwa wersji"
                    ),
                ),
                (
                    "pallet_code",
                    models.CharField(
                        choices=[
                            ("Z129", "Z129 (129×80 cm)"),
                            ("EU", "EU (120×80 cm)"),
                            ("IND", "IND (120×100 cm)"),
                            ("HALF", "HALF (80×60 cm)"),
                        ],
                        default="Z129",
                        max_length=20,
                        verbose_name="Typ palety",
                    ),
                ),
                ("pallet_length_cm", models.IntegerField(default=129)),
                ("pallet_width_cm", models.IntegerField(default=80)),
                (
                    "max_height_total_cm",
                    models.IntegerField(
                        default=215, verbose_name="Wys. max total [cm]"
                    ),
                ),
                ("pallet_base_height_cm", models.IntegerField(default=15)),
                (
                    "max_weight_kg",
                    models.IntegerField(default=1000, verbose_name="Max waga [kg]"),
                ),
                ("carton_l", models.IntegerField(verbose_name="L kartonu [cm]")),
                ("carton_w", models.IntegerField(verbose_name="W kartonu [cm]")),
                ("carton_h", models.IntegerField(verbose_name="H kartonu [cm]")),
                ("unit_weight", models.FloatField(verbose_name="Waga jedn. [kg]")),
                (
                    "pcs_per_carton",
                    models.IntegerField(default=1, verbose_name="Szt / karton"),
                ),
                (
                    "carton_tare",
                    models.FloatField(default=0.0, verbose_name="Tara kartonu [kg]"),
                ),
                (
                    "demand_pcs",
                    models.IntegerField(default=1000, verbose_name="Popyt [szt]"),
                ),
                ("layouts", models.JSONField(default=list)),
                (
                    "selected_layout",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Wybrany layout"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktywna"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="Uwagi dla magazyniera"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "carton",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="instructions",
                        to="ui.carton",
                        verbose_name="Karton z bazy",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instructions",
                        to="ui.product",
                        verbose_name="Produkt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instrukcja paletyzacji",
                "verbose_name_plural": "Instrukcje paletyzacji",
                "ordering": ["product", "version"],
                "unique_together": {("product", "version")},
            },
        ),
        migrations.CreateModel(
            name="ErrorReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_code",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Kod produktu"
                    ),
                ),
                (
                    "reporter_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Imię/nick"
                    ),
                ),
                (
                    "reporter_location",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Lokalizacja (magazyn/stanowisko)",
                    ),
                ),
                ("description", models.TextField(verbose_name="Opis błędu")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Nowe"),
                            ("in_review", "W trakcie"),
                            ("resolved", "Rozwiązane"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, verbose_name="Notatki admina"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "instruction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="ui.palletizationinstruction",
                        verbose_name="Instrukcja",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zgłoszenie błędu",
                "verbose_name_plural": "Zgłoszenia błędów",
                "ordering": ["-created_at"],
            },
        ),
    ]
