# Generated by Django 5.2.14 on 2026-05-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0002_carton_product_palletizationinstruction_errorreport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batch",
            name="pallet_code",
            field=models.CharField(default="EU", max_length=20),
        ),
        migrations.AlterField(
            model_name="batch",
            name="pallet_length_cm",
            field=models.IntegerField(default=120),
        ),
        migrations.AlterField(
            model_name="palletizationinstruction",
            name="pallet_code",
            field=models.CharField(
                choices=[("EU", "Euro (120×80 cm)")],
                default="EU",
                max_length=20,
                verbose_name="Typ palety",
            ),
        ),
    ]
