# Generated by Django 5.2.14 on 2026-05-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0003_alter_batch_pallet_code_alter_batch_pallet_length_cm_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WarehouseLocationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nazwa lokalizacji"),
                ),
                (
                    "width_cm",
                    models.IntegerField(
                        help_text="Światło w miejscu paletowym",
                        verbose_name="Szerokość [cm]",
                    ),
                ),
                ("depth_cm", models.IntegerField(verbose_name="Głębokość [cm]")),
                (
                    "total_height_cm",
                    models.IntegerField(verbose_name="Wysokość całkowita [cm]"),
                ),
                (
                    "pallet_height_cm",
                    models.IntegerField(default=15, verbose_name="Wys. palety [cm]"),
                ),
                (
                    "manipulation_margin_cm",
                    models.IntegerField(
                        default=20,
                        help_text="Wolna przestrzeń na wstawienie wózkiem",
                        verbose_name="Margines manipulacji [cm]",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Uwagi")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktywna"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Typ lokalizacji",
                "verbose_name_plural": "Typy lokalizacji",
                "ordering": ["name"],
            },
        ),
    ]
