# Generated by Django 5.2.14 on 2026-05-23 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0004_warehouselocationtype"),
    ]

    operations = [
        migrations.CreateModel(
            name="InnerPack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=250, verbose_name="Nazwa opakowania zbiorczego"
                    ),
                ),
                ("length_cm", models.FloatField(verbose_name="L [cm]")),
                ("width_cm", models.FloatField(verbose_name="W [cm]")),
                ("height_cm", models.FloatField(verbose_name="H [cm]")),
                (
                    "units_per_pack",
                    models.IntegerField(default=1, verbose_name="Szt / opakowanie"),
                ),
                (
                    "tare_kg",
                    models.FloatField(default=0.0, verbose_name="Tara opakowania [kg]"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Uwagi")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktywne"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Opakowanie zbiorcze",
                "verbose_name_plural": "Opakowania zbiorcze",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="carton",
            name="packs_per_carton",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Opakowań w kartonie"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="unit_height_cm",
            field=models.FloatField(
                blank=True, null=True, verbose_name="H sztuki [cm]"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="unit_length_cm",
            field=models.FloatField(
                blank=True, null=True, verbose_name="L sztuki [cm]"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="unit_width_cm",
            field=models.FloatField(
                blank=True, null=True, verbose_name="W sztuki [cm]"
            ),
        ),
        migrations.AddField(
            model_name="carton",
            name="inner_pack",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cartons",
                to="ui.innerpack",
                verbose_name="Opakowanie zbiorcze",
            ),
        ),
    ]
