# Generated by Django 5.2.14 on 2026-05-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0005_innerpack_product_unit_dims"),
    ]

    operations = [
        migrations.AlterField(
            model_name="palletizationinstruction",
            name="pallet_length_cm",
            field=models.IntegerField(default=120),
        ),
    ]
