# Generated by Django 5.2.14 on 2026-05-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0006_fix_pallet_length_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="innerpack",
            name="sales_unit_h_cm",
            field=models.FloatField(
                blank=True, null=True, verbose_name="H opak. handlowego [cm]"
            ),
        ),
        migrations.AddField(
            model_name="innerpack",
            name="sales_unit_l_cm",
            field=models.FloatField(
                blank=True, null=True, verbose_name="L opak. handlowego [cm]"
            ),
        ),
        migrations.AddField(
            model_name="innerpack",
            name="sales_unit_w_cm",
            field=models.FloatField(
                blank=True, null=True, verbose_name="W opak. handlowego [cm]"
            ),
        ),
        migrations.AddField(
            model_name="innerpack",
            name="sales_units_per_pack",
            field=models.IntegerField(
                default=1, verbose_name="Opak. handlowych / zbiorcze"
            ),
        ),
    ]
