# Generated by Django 5.2.14 on 2026-05-23 22:32

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0007_add_sales_unit_to_innerpack"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalCarton",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=250, verbose_name="Nazwa opakowania"),
                ),
                (
                    "ean",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="EAN opakowania"
                    ),
                ),
                ("length_cm", models.IntegerField(verbose_name="L [cm]")),
                ("width_cm", models.IntegerField(verbose_name="W [cm]")),
                ("height_cm", models.IntegerField(verbose_name="H [cm]")),
                ("unit_weight_kg", models.FloatField(verbose_name="Waga jedn. [kg]")),
                (
                    "pieces_per_carton",
                    models.IntegerField(default=1, verbose_name="Szt / karton"),
                ),
                (
                    "tare_kg",
                    models.FloatField(default=0.0, verbose_name="Tara kartonu [kg]"),
                ),
                (
                    "packs_per_carton",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Opakowań w kartonie"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Uwagi")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktywny"),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inner_pack",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="ui.innerpack",
                        verbose_name="Opakowanie zbiorcze",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Karton",
                "verbose_name_plural": "historical Kartony",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalInnerPack",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=250, verbose_name="Nazwa opakowania zbiorczego"
                    ),
                ),
                ("length_cm", models.FloatField(verbose_name="L [cm]")),
                ("width_cm", models.FloatField(verbose_name="W [cm]")),
                ("height_cm", models.FloatField(verbose_name="H [cm]")),
                (
                    "units_per_pack",
                    models.IntegerField(default=1, verbose_name="Szt / opakowanie"),
                ),
                (
                    "tare_kg",
                    models.FloatField(default=0.0, verbose_name="Tara opakowania [kg]"),
                ),
                (
                    "sales_unit_l_cm",
                    models.FloatField(
                        blank=True, null=True, verbose_name="L opak. handlowego [cm]"
                    ),
                ),
                (
                    "sales_unit_w_cm",
                    models.FloatField(
                        blank=True, null=True, verbose_name="W opak. handlowego [cm]"
                    ),
                ),
                (
                    "sales_unit_h_cm",
                    models.FloatField(
                        blank=True, null=True, verbose_name="H opak. handlowego [cm]"
                    ),
                ),
                (
                    "sales_units_per_pack",
                    models.IntegerField(
                        default=1, verbose_name="Opak. handlowych / zbiorcze"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Uwagi")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktywne"),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Opakowanie zbiorcze",
                "verbose_name_plural": "historical Opakowania zbiorcze",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPalletizationInstruction",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="Wersja"),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="Nazwa wersji"
                    ),
                ),
                (
                    "pallet_code",
                    models.CharField(
                        choices=[("EU", "Euro (120×80 cm)")],
                        default="EU",
                        max_length=20,
                        verbose_name="Typ palety",
                    ),
                ),
                ("pallet_length_cm", models.IntegerField(default=120)),
                ("pallet_width_cm", models.IntegerField(default=80)),
                (
                    "max_height_total_cm",
                    models.IntegerField(
                        default=215, verbose_name="Wys. max total [cm]"
                    ),
                ),
                ("pallet_base_height_cm", models.IntegerField(default=15)),
                (
                    "max_weight_kg",
                    models.IntegerField(default=1000, verbose_name="Max waga [kg]"),
                ),
                ("carton_l", models.IntegerField(verbose_name="L kartonu [cm]")),
                ("carton_w", models.IntegerField(verbose_name="W kartonu [cm]")),
                ("carton_h", models.IntegerField(verbose_name="H kartonu [cm]")),
                ("unit_weight", models.FloatField(verbose_name="Waga jedn. [kg]")),
                (
                    "pcs_per_carton",
                    models.IntegerField(default=1, verbose_name="Szt / karton"),
                ),
                (
                    "carton_tare",
                    models.FloatField(default=0.0, verbose_name="Tara kartonu [kg]"),
                ),
                (
                    "demand_pcs",
                    models.IntegerField(default=1000, verbose_name="Popyt [szt]"),
                ),
                (
                    "selected_layout",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Wybrany layout"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktywna"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="Uwagi dla magazyniera"),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "carton",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="ui.carton",
                        verbose_name="Karton z bazy",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="ui.product",
                        verbose_name="Produkt",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Instrukcja paletyzacji",
                "verbose_name_plural": "historical Instrukcje paletyzacji",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalProduct",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Kod indeksu"
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="Nazwa")),
                ("description", models.TextField(blank=True, verbose_name="Opis")),
                (
                    "ean",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="EAN / barcode"
                    ),
                ),
                (
                    "unit_length_cm",
                    models.FloatField(
                        blank=True, null=True, verbose_name="L sztuki [cm]"
                    ),
                ),
                (
                    "unit_width_cm",
                    models.FloatField(
                        blank=True, null=True, verbose_name="W sztuki [cm]"
                    ),
                ),
                (
                    "unit_height_cm",
                    models.FloatField(
                        blank=True, null=True, verbose_name="H sztuki [cm]"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktywny"),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Produkt",
                "verbose_name_plural": "historical Produkty",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
