# Generated by Django 5.2.14 on 2026-05-24 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0008_historicalcarton_historicalinnerpack_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WarehouseSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nazwa")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("row_count", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="WarehouseSnapshotRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location_code", models.CharField(max_length=50)),
                (
                    "product_code",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("quantity", models.FloatField(default=0)),
                ("aisle", models.CharField(blank=True, default="", max_length=10)),
                ("rack", models.CharField(blank=True, default="", max_length=10)),
                ("col", models.CharField(blank=True, default="", max_length=10)),
                ("level", models.IntegerField(blank=True, null=True)),
                ("has_product", models.BooleanField(default=False)),
                ("product_in_master", models.BooleanField(default=False)),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="ui.warehousesnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["location_code"],
            },
        ),
    ]
