# Generated by Django 5.2.14 on 2026-05-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0009_warehousesnapshot_warehousesnapshotrow"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="warehousesnapshotrow",
            name="col",
        ),
        migrations.RemoveField(
            model_name="warehousesnapshotrow",
            name="has_product",
        ),
        migrations.RemoveField(
            model_name="warehousesnapshotrow",
            name="product_code",
        ),
        migrations.RemoveField(
            model_name="warehousesnapshotrow",
            name="product_in_master",
        ),
        migrations.RemoveField(
            model_name="warehousesnapshotrow",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="warehousesnapshotrow",
            name="rack",
        ),
        migrations.AddField(
            model_name="warehousesnapshot",
            name="blocked_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="warehousesnapshot",
            name="occupied_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="warehousesnapshotrow",
            name="blocked_pick",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="warehousesnapshotrow",
            name="blocked_put",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="warehousesnapshotrow",
            name="capacity_mm",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="warehousesnapshotrow",
            name="col_code",
            field=models.CharField(blank=True, default="", max_length=5),
        ),
        migrations.AddField(
            model_name="warehousesnapshotrow",
            name="col_idx",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="warehousesnapshotrow",
            name="is_empty",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="warehousesnapshotrow",
            name="section",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="warehousesnapshotrow",
            name="stack",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="warehousesnapshotrow",
            name="storage_group",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="warehousesnapshotrow",
            name="warehouse_type",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="warehousesnapshotrow",
            name="zone",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="warehousesnapshotrow",
            name="level",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="warehousesnapshotrow",
            name="location_code",
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
