# Generated by Django 5.2.14 on 2026-05-24 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0010_remove_warehousesnapshotrow_col_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WarehouseLayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Layout", max_length=200)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("location_count", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="WarehouseLayoutCell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location_code", models.CharField(db_index=True, max_length=50)),
                ("grid_row", models.IntegerField()),
                ("grid_col", models.IntegerField()),
                ("level", models.IntegerField(default=1)),
                (
                    "layout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cells",
                        to="ui.warehouselayout",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["layout", "grid_row", "grid_col"],
                        name="ui_warehous_layout__726606_idx",
                    )
                ],
                "unique_together": {("layout", "location_code")},
            },
        ),
    ]
