# Generated by Django 5.2.14 on 2026-05-24 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0011_warehouselayout_warehouselayoutcell"),
    ]

    operations = [
        migrations.CreateModel(
            name="WarehouseLocationMasterBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("location_count", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="WarehouseLocationMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location_code", models.CharField(db_index=True, max_length=50)),
                ("level", models.IntegerField(default=1)),
                (
                    "warehouse_type",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("height_mm", models.IntegerField(default=0)),
                ("max_volume_m3", models.FloatField(default=0.0)),
                ("max_weight_kg", models.FloatField(default=0.0)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="ui.warehouselocationmasterbatch",
                    ),
                ),
            ],
            options={
                "unique_together": {("batch", "location_code")},
            },
        ),
    ]
