# Generated by Django 5.2.14 on 2026-05-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0012_warehouselocationmasterbatch_warehouselocationmaster"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehouselocationmaster",
            name="depth_mm",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="warehouselocationmaster",
            name="width_mm",
            field=models.IntegerField(default=0),
        ),
    ]
