# Generated by Django 5.2.14 on 2026-05-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0013_add_width_depth_to_location_master"),
    ]

    operations = [
        migrations.CreateModel(
            name="WarehouseRackType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Kod typu"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nazwa")),
                (
                    "width_mm",
                    models.IntegerField(
                        default=800, verbose_name="Szer. fiz. miejsca [mm]"
                    ),
                ),
                (
                    "manip_mm",
                    models.IntegerField(
                        default=900, verbose_name="Szer. z manipulacją [mm]"
                    ),
                ),
                (
                    "depth_mm",
                    models.IntegerField(default=1100, verbose_name="Głębokość [mm]"),
                ),
                (
                    "max_weight_kg",
                    models.FloatField(default=1200, verbose_name="Max waga [kg]"),
                ),
                (
                    "max_volume_m3",
                    models.FloatField(default=2.5, verbose_name="Max objętość [m³]"),
                ),
                (
                    "level_heights",
                    models.JSONField(
                        default=dict, verbose_name="Wysokości poziomów [mm]"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#f59e0b", max_length=7, verbose_name="Kolor 3D"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Typ lokalizacji",
                "verbose_name_plural": "Typy lokalizacji",
                "ordering": ["code"],
            },
        ),
    ]
