# Generated by Django 5.2.14 on 2026-05-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0014_add_warehouse_rack_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        unique=True,
                        verbose_name="Kod materiału",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=250, verbose_name="Nazwa"),
                ),
                (
                    "supplier_short",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Skrót dostawcy"
                    ),
                ),
                (
                    "supplier_full",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Pełna nazwa dostawcy"
                    ),
                ),
                (
                    "width_cm",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Szerokość [cm]"
                    ),
                ),
                (
                    "height_cm",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Wysokość [cm]"
                    ),
                ),
                (
                    "length_cm",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Długość [cm]"
                    ),
                ),
                (
                    "gross_kg",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Waga brutto [kg]"
                    ),
                ),
                (
                    "pieces_per_carton",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Szt/karton"
                    ),
                ),
                (
                    "ean",
                    models.CharField(blank=True, max_length=30, verbose_name="EAN"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Materiał referencyjny",
                "verbose_name_plural": "Materiały referencyjne",
                "ordering": ["code"],
            },
        ),
        migrations.AddField(
            model_name="historicalproduct",
            name="supplier_short",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Dostawca (skrót)"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="supplier_short",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Dostawca (skrót)"
            ),
        ),
    ]
