# Generated by Django 5.2.14 on 2026-05-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0015_add_material_reference_and_product_supplier"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehouselocationtype",
            name="is_pallet_location",
            field=models.BooleanField(
                default=True,
                help_text="Towar wstawiany jest na palecie (odlicza wys. palety od podstawy)",
                verbose_name="Lokalizacja paletowa",
            ),
        ),
        migrations.AddField(
            model_name="warehouselocationtype",
            name="location_class",
            field=models.CharField(
                choices=[
                    ("pallet_full", "Paletowe pełne (≥80 cm)"),
                    ("pallet_half", "Półpaletowe (40–79 cm)"),
                    ("floor", "Podłogowe / BLC"),
                    ("shelf", "Półkowe"),
                    ("other", "Inne"),
                ],
                default="pallet_full",
                max_length=20,
                verbose_name="Klasa lokalizacji",
            ),
        ),
        migrations.AddField(
            model_name="warehouselocationtype",
            name="max_load_kg",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Max obciążenie [kg]"
            ),
        ),
    ]
