# Generated by Django 5.2.14 on 2026-05-25 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0016_add_location_class_pallet_flag_maxload"),
    ]

    operations = [
        migrations.CreateModel(
            name="Carrier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nazwa przewoźnika"),
                ),
                (
                    "carrier_type",
                    models.CharField(
                        choices=[
                            ("courier", "Kurier (paczki)"),
                            ("ltl", "Drobnica LTL"),
                            ("ftl", "Całopojazdowy FTL"),
                        ],
                        default="ltl",
                        max_length=20,
                        verbose_name="Typ",
                    ),
                ),
                (
                    "dim_weight_divisor",
                    models.FloatField(
                        default=5000, verbose_name="Dzielnik wagi obj. [cm³/kg]"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktywny"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Uwagi")),
            ],
            options={
                "ordering": ["carrier_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nazwa przesyłki"),
                ),
                (
                    "destination_country",
                    models.CharField(
                        blank=True, max_length=2, verbose_name="Kraj docelowy (ISO)"
                    ),
                ),
                (
                    "destination_city",
                    models.CharField(blank=True, max_length=100, verbose_name="Miasto"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Robocze"),
                            ("confirmed", "Zatwierdzone"),
                            ("sent", "Wysłane"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Uwagi")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CarrierZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Strefa / kraj"),
                ),
                (
                    "countries",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        verbose_name="Kody krajów ISO (przecinek)",
                    ),
                ),
                (
                    "carrier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zones",
                        to="ui.carrier",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CarrierRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight_from_kg",
                    models.FloatField(default=0, verbose_name="Waga od [kg]"),
                ),
                (
                    "weight_to_kg",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Waga do [kg] (puste = bez limitu)",
                    ),
                ),
                (
                    "price_eur",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Cena [EUR]"
                    ),
                ),
                (
                    "per_pallet_eur",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Dopłata/paleta [EUR]",
                    ),
                ),
                (
                    "fuel_surcharge_pct",
                    models.FloatField(default=0, verbose_name="Dopłata paliwowa [%]"),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=200, verbose_name="Uwagi"),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates",
                        to="ui.carrierzone",
                    ),
                ),
            ],
            options={
                "ordering": ["weight_from_kg"],
            },
        ),
        migrations.CreateModel(
            name="ShipmentLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.FloatField(verbose_name="Ilość")),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("szt", "Sztuki (szt)"),
                            ("kar", "Kartony (KAR)"),
                            ("pal", "Palety"),
                        ],
                        default="kar",
                        max_length=10,
                        verbose_name="Jednostka",
                    ),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=200, verbose_name="Uwagi"),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ui.product",
                        verbose_name="Produkt",
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="ui.shipment",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
