# Generated by Django 5.2.14 on 2026-05-25 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0017_add_shipment_carrier"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpalletizationinstruction",
            name="inner_pack",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="ui.innerpack",
                verbose_name="Opakowanie zbiorcze",
            ),
        ),
        migrations.AddField(
            model_name="historicalpalletizationinstruction",
            name="packs_per_carton",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Opakowań zbiorczych / karton"
            ),
        ),
        migrations.AddField(
            model_name="historicalpalletizationinstruction",
            name="pcs_per_inner_pack",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Szt / opakowanie zbiorcze"
            ),
        ),
        migrations.AddField(
            model_name="palletizationinstruction",
            name="inner_pack",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="instructions",
                to="ui.innerpack",
                verbose_name="Opakowanie zbiorcze",
            ),
        ),
        migrations.AddField(
            model_name="palletizationinstruction",
            name="packs_per_carton",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Opakowań zbiorczych / karton"
            ),
        ),
        migrations.AddField(
            model_name="palletizationinstruction",
            name="pcs_per_inner_pack",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Szt / opakowanie zbiorcze"
            ),
        ),
        migrations.AlterField(
            model_name="historicalinnerpack",
            name="units_per_pack",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Szt / opakowanie (opcjonalnie)"
            ),
        ),
        migrations.AlterField(
            model_name="innerpack",
            name="units_per_pack",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Szt / opakowanie (opcjonalnie)"
            ),
        ),
    ]
