# Generated by Django 5.2.14 on 2026-05-26 02:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0018_add_inner_pack_to_instruction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carrier",
            name="dim_weight_divisor",
            field=models.FloatField(
                default=5000,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Dzielnik wagi obj. [cm³/kg]",
            ),
        ),
        migrations.AlterField(
            model_name="carrierrate",
            name="fuel_surcharge_pct",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=6,
                verbose_name="Dopłata paliwowa [%]",
            ),
        ),
        migrations.AlterField(
            model_name="carrierrate",
            name="weight_from_kg",
            field=models.DecimalField(
                decimal_places=3, default=0, max_digits=10, verbose_name="Waga od [kg]"
            ),
        ),
        migrations.AlterField(
            model_name="carrierrate",
            name="weight_to_kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=10,
                null=True,
                verbose_name="Waga do [kg] (puste = bez limitu)",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="shipmentline",
            unique_together={("shipment", "product")},
        ),
    ]
