# Generated by Django 5.2.14 on 2026-05-26 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0019_fix_carrier_rate_decimal_and_shipmentline_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nazwa kategorii"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Krótki identyfikator np. KUBKI",
                        max_length=20,
                        unique=True,
                        verbose_name="Kod kategorii",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#3b82f6",
                        help_text="Hex np. #3b82f6",
                        max_length=7,
                        verbose_name="Kolor",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Opis")),
            ],
            options={
                "verbose_name": "Kategoria produktu",
                "verbose_name_plural": "Kategorie produktów",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WarehouseModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nazwa modelu")),
                ("notes", models.TextField(blank=True, verbose_name="Uwagi")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "floor_width_m",
                    models.FloatField(default=50, verbose_name="Szerokość hali [m]"),
                ),
                (
                    "floor_depth_m",
                    models.FloatField(default=30, verbose_name="Głębokość hali [m]"),
                ),
            ],
            options={
                "verbose_name": "Model magazynu",
                "verbose_name_plural": "Modele magazynów",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="historicalproduct",
            name="category",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="ui.productcategory",
                verbose_name="Kategoria",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="ui.productcategory",
                verbose_name="Kategoria",
            ),
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("in", "Przyjęcie"),
                            ("out", "Wydanie"),
                            ("adj", "Korekta"),
                        ],
                        max_length=5,
                        verbose_name="Kierunek",
                    ),
                ),
                ("quantity_pcs", models.FloatField(verbose_name="Ilość [szt]")),
                (
                    "location_code",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Kod lokalizacji"
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Referencja (nr dok.)"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Uwagi")),
                ("movement_date", models.DateField(verbose_name="Data ruchu")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Zarejestrował"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="ui.product",
                        verbose_name="Produkt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ruch towarowy",
                "verbose_name_plural": "Ruchy towarowe",
                "ordering": ["-movement_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WarehouseModelRack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "zone",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="Strefa"
                    ),
                ),
                ("rack_id", models.CharField(max_length=20, verbose_name="Nr regału")),
                (
                    "n_bays",
                    models.IntegerField(default=1, verbose_name="Liczba boków (bays)"),
                ),
                (
                    "n_levels",
                    models.IntegerField(default=3, verbose_name="Liczba poziomów"),
                ),
                (
                    "bay_width_cm",
                    models.IntegerField(
                        default=100, verbose_name="Szerokość boku [cm]"
                    ),
                ),
                (
                    "depth_cm",
                    models.IntegerField(
                        default=80, verbose_name="Głębokość regału [cm]"
                    ),
                ),
                (
                    "level_height_cm",
                    models.IntegerField(default=200, verbose_name="Wys. poziomów [cm]"),
                ),
                (
                    "x_m",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Pozycja X [m]"
                    ),
                ),
                (
                    "y_m",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Pozycja Y [m]"
                    ),
                ),
                (
                    "angle_deg",
                    models.FloatField(default=0, verbose_name="Kąt obrotu [°]"),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="racks",
                        to="ui.warehousemodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Regał modelu",
                "verbose_name_plural": "Regały modelu",
                "ordering": ["zone", "rack_id"],
                "unique_together": {("model", "zone", "rack_id")},
            },
        ),
    ]
