# Generated by Django 5.2.14 on 2026-05-27 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0020_add_categories_movements_warehouse_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="PickerActivityBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nazwa importu"),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("row_count", models.IntegerField(default=0)),
                ("date_from", models.DateField(blank=True, null=True)),
                ("date_to", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Partia aktywności pickerów",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="PickerActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location_code", models.CharField(db_index=True, max_length=50)),
                ("confirmed_at", models.DateTimeField(db_index=True)),
                (
                    "picker_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("task_type", models.CharField(blank=True, default="", max_length=50)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="ui.pickeractivitybatch",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["batch", "confirmed_at"],
                        name="ui_pickerac_batch_i_2e2de0_idx",
                    ),
                    models.Index(
                        fields=["batch", "location_code"],
                        name="ui_pickerac_batch_i_abdb41_idx",
                    ),
                ],
            },
        ),
    ]
