# Generated by Django 5.2.14 on 2026-05-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0021_picker_activity_heatmap"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehouseracktype",
            name="level_cols",
            field=models.JSONField(
                default=dict,
                help_text='np. {"1":1,"2":2,"3":1} — ile kolumn na każdym poziomie. Puste = 1 wszędzie.',
                verbose_name="Kolumny per poziom",
            ),
        ),
    ]
