# Generated by Django 5.2.14 on 2026-05-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0022_rack_type_level_cols"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpalletizationinstruction",
            name="custom_layers",
            field=models.JSONField(
                default=list,
                help_text="Lista warstw z ręcznie ułożonymi kartonami",
                verbose_name="Warstwy niestandardowe",
            ),
        ),
        migrations.AddField(
            model_name="palletizationinstruction",
            name="custom_layers",
            field=models.JSONField(
                default=list,
                help_text="Lista warstw z ręcznie ułożonymi kartonami",
                verbose_name="Warstwy niestandardowe",
            ),
        ),
    ]
