# Generated by Django 5.2.15 on 2026-06-16 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0023_pallet_custom_layers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="warehouselayoutcell",
            options={"ordering": ["layout", "id"]},
        ),
        migrations.AlterModelOptions(
            name="warehouselocationmaster",
            options={"ordering": ["location_code", "id"]},
        ),
        migrations.AlterModelOptions(
            name="warehousesnapshotrow",
            options={"ordering": ["location_code", "id"]},
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="movement_date",
            field=models.DateField(db_index=True, verbose_name="Data ruchu"),
        ),
    ]
