# Generated by Django 5.2.15 on 2026-06-17 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0024_alter_warehouselayoutcell_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="carton",
            name="layout_design",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Zaprojektowany układ na palecie"
            ),
        ),
        migrations.AddField(
            model_name="historicalcarton",
            name="layout_design",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Zaprojektowany układ na palecie"
            ),
        ),
    ]
