# Generated by Django 5.2.15 on 2026-06-17 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0025_carton_layout_design_historicalcarton_layout_design"),
    ]

    operations = [
        migrations.CreateModel(
            name="CartonArtwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "face",
                    models.CharField(
                        choices=[
                            ("front", "Front"),
                            ("back", "Tył"),
                            ("left", "Lewy bok"),
                            ("right", "Prawy bok"),
                            ("top", "Góra"),
                            ("bottom", "Dół"),
                        ],
                        default="front",
                        max_length=10,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("print", "Nadruk ściany"),
                            ("label", "Etykieta / naklejka"),
                        ],
                        default="label",
                        max_length=10,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="carton_artwork/", verbose_name="Grafika"
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=120, verbose_name="Nazwa"),
                ),
                ("x_pct", models.FloatField(default=8)),
                ("y_pct", models.FloatField(default=8)),
                ("w_pct", models.FloatField(default=30)),
                ("h_pct", models.FloatField(default=20)),
                ("rotation_deg", models.FloatField(default=0)),
                ("z", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "carton",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artworks",
                        to="ui.carton",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grafika kartonu",
                "verbose_name_plural": "Grafiki kartonu",
                "ordering": ["face", "z", "id"],
            },
        ),
    ]
