# Generated by Django 5.2.15 on 2026-06-17 16:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0026_cartonartwork"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="stowage_efficiency_pct",
            field=models.IntegerField(
                default=80,
                help_text="Realny stopień wykorzystania kubatury palety przy ręcznym układaniu (mieszane SKU nigdy nie pakują się w 100%). Niższa wartość → więcej palet.",
                validators=[
                    django.core.validators.MinValueValidator(30),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Efektywność układania [%]",
            ),
        ),
    ]
