# Generated by Django 5.2.15 on 2026-06-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0027_shipment_stowage_efficiency_pct"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpalletizationinstruction",
            name="units_per_piece",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Szt użytkowych (JU) / jednostkę"
            ),
        ),
        migrations.AddField(
            model_name="palletizationinstruction",
            name="units_per_piece",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Szt użytkowych (JU) / jednostkę"
            ),
        ),
    ]
