# Generated by Django 5.2.15 on 2026-06-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0028_historicalpalletizationinstruction_units_per_piece_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipmentline",
            name="source_unit",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Jedn. źródłowa"
            ),
        ),
    ]
