# Generated by Django 5.2.15 on 2026-06-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0029_shipmentline_source_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="author",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Autor dostawy"
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="author_email",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="E-mail autora"
            ),
        ),
    ]
