# Generated by Django 5.2.15 on 2026-06-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0030_shipment_author_shipment_author_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuoteRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=120, verbose_name="Nazwa / firma"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktywny"),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=200, verbose_name="Uwagi"),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
