# Generated by Django 5.2.15 on 2026-06-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0031_quoterecipient"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="destination_postal",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Kod pocztowy"
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="recipient_name",
            field=models.CharField(blank=True, max_length=200, verbose_name="Odbiorca"),
        ),
    ]
