# Generated by Django 5.2.15 on 2026-06-18 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0032_shipment_destination_postal_shipment_recipient_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="HandlingUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seq",
                    models.PositiveIntegerField(default=1, verbose_name="Nr palety"),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=64,
                        verbose_name="Kod HU / SSCC",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Zaplanowany"),
                            ("ok", "Zgodny"),
                            ("mismatch", "Rozbieżność"),
                        ],
                        default="planned",
                        max_length=12,
                        verbose_name="Status",
                    ),
                ),
                (
                    "scanned",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Zeskanowano"
                    ),
                ),
                (
                    "discrepancies",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Rozbieżności"
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("verified_source", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="handling_units",
                        to="ui.shipment",
                    ),
                ),
            ],
            options={
                "ordering": ["shipment", "seq"],
                "unique_together": {("shipment", "seq")},
            },
        ),
        migrations.CreateModel(
            name="HandlingUnitItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ref_code", models.CharField(max_length=50, verbose_name="Kod / REF")),
                (
                    "expected_qty",
                    models.FloatField(default=0, verbose_name="Oczekiwana ilość"),
                ),
                (
                    "unit",
                    models.CharField(
                        default="kar", max_length=20, verbose_name="Jednostka"
                    ),
                ),
                (
                    "hu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="ui.handlingunit",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ui.product",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
