# Generated by Django 5.2.15 on 2026-06-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0033_handlingunit_handlingunititem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="handlingunit",
            name="code",
            field=models.CharField(
                blank=True, db_index=True, max_length=64, verbose_name="pickHU"
            ),
        ),
    ]
