# Generated by Django 5.2.15 on 2026-06-18 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0034_alter_handlingunit_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="handlingunit",
            name="discrepancies",
        ),
        migrations.RemoveField(
            model_name="handlingunit",
            name="scanned",
        ),
        migrations.RemoveField(
            model_name="handlingunit",
            name="verified_source",
        ),
        migrations.AddField(
            model_name="handlingunit",
            name="controlled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="controlled_hus",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="handlingunit",
            name="location",
            field=models.CharField(
                blank=True, max_length=40, verbose_name="Lokalizacja"
            ),
        ),
        migrations.AddField(
            model_name="handlingunit",
            name="recipient_type",
            field=models.CharField(
                blank=True, max_length=40, verbose_name="Typ odbiorcy"
            ),
        ),
        migrations.AddField(
            model_name="handlingunit",
            name="warehouse_type",
            field=models.CharField(
                blank=True, max_length=40, verbose_name="Typ magazynu"
            ),
        ),
        migrations.AddField(
            model_name="handlingunititem",
            name="alt_qty",
            field=models.FloatField(default=0, verbose_name="Ilość AJM"),
        ),
        migrations.AddField(
            model_name="handlingunititem",
            name="alt_unit",
            field=models.CharField(
                default="KAR", max_length=20, verbose_name="Jedn. alternatywna (AJM)"
            ),
        ),
        migrations.AddField(
            model_name="handlingunititem",
            name="base_qty",
            field=models.FloatField(default=0, verbose_name="Ilość JP"),
        ),
        migrations.AddField(
            model_name="handlingunititem",
            name="base_unit",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Jedn. podstawowa (JP)"
            ),
        ),
        migrations.AddField(
            model_name="handlingunititem",
            name="controlled",
            field=models.BooleanField(default=False, verbose_name="Skontrolowano"),
        ),
        migrations.AddField(
            model_name="handlingunititem",
            name="controlled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="handlingunititem",
            name="counted_qty",
            field=models.FloatField(blank=True, null=True, verbose_name="Zliczono"),
        ),
        migrations.AddField(
            model_name="handlingunititem",
            name="counted_unit",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="handlingunititem",
            name="description",
            field=models.CharField(blank=True, max_length=120, verbose_name="Opis"),
        ),
        migrations.AddField(
            model_name="handlingunititem",
            name="error_flags",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Flagi błędów"
            ),
        ),
        migrations.AddField(
            model_name="handlingunititem",
            name="expiry",
            field=models.DateField(blank=True, null=True, verbose_name="Data ważności"),
        ),
        migrations.AddField(
            model_name="handlingunititem",
            name="lot",
            field=models.CharField(
                blank=True, max_length=16, verbose_name="LOT producenta"
            ),
        ),
        migrations.AddField(
            model_name="handlingunititem",
            name="result",
            field=models.CharField(
                choices=[("", "—"), ("ok", "Potwierdzony"), ("error", "Błąd")],
                default="",
                max_length=8,
                verbose_name="Wynik",
            ),
        ),
        migrations.AlterField(
            model_name="handlingunit",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "Zaplanowany"),
                    ("in_control", "W kontroli"),
                    ("ok", "Zgodny"),
                    ("to_recheck", "Do rekontroli"),
                ],
                default="planned",
                max_length=12,
                verbose_name="Status",
            ),
        ),
    ]
