# Generated by Django 5.2.15 on 2026-06-18 17:02

import django.db.models.deletion
import ui.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0035_remove_handlingunit_discrepancies_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShipmentQuoteOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "carrier_name",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Spedycja"
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        db_index=True,
                        default=ui.models._quote_token,
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Kwota",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="PLN", max_length=3, verbose_name="Waluta"
                    ),
                ),
                (
                    "truck_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Podstawienie auta"
                    ),
                ),
                (
                    "delivery_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data dostawy"
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Uwagi spedycji"
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ui.quoterecipient",
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quote_offers",
                        to="ui.shipment",
                    ),
                ),
            ],
            options={
                "ordering": ["amount"],
                "unique_together": {("shipment", "recipient")},
            },
        ),
    ]
