# Generated by Django 5.2.15 on 2026-06-18 17:14

import django.db.models.deletion
import ui.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0036_shipmentquoteoffer"),
    ]

    operations = [
        migrations.CreateModel(
            name="WarehouseReadiness",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("pre", "Gotowość wstępna (15 min)"),
                            ("date", "Gotowość na datę odbioru"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        db_index=True,
                        default=ui.models._quote_token,
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Oczekuje"),
                            ("yes", "Potwierdzone"),
                            ("no", "Odmowa"),
                        ],
                        default="pending",
                        max_length=8,
                    ),
                ),
                (
                    "pickup_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data odbioru"
                    ),
                ),
                ("requested_at", models.DateTimeField(blank=True, null=True)),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                ("answered_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=300)),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wh_confirmations",
                        to="ui.shipment",
                    ),
                ),
            ],
            options={
                "ordering": ["kind"],
                "unique_together": {("shipment", "kind")},
            },
        ),
    ]
