# Generated by Django 5.2.15 on 2026-06-18 17:21

import django.db.models.deletion
import ui.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0037_warehousereadiness"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipmentquoteoffer",
            name="selected",
            field=models.BooleanField(default=False, verbose_name="Wybrana"),
        ),
        migrations.CreateModel(
            name="DriverAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "form_token",
                    models.CharField(
                        db_index=True,
                        default=ui.models._quote_token,
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "confirm_token",
                    models.CharField(
                        db_index=True,
                        default=ui.models._quote_token,
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "driver_name",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Kierowca"
                    ),
                ),
                (
                    "driver_plate",
                    models.CharField(blank=True, max_length=20, verbose_name="Nr auta"),
                ),
                (
                    "driver_phone",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="Telefon kierowcy"
                    ),
                ),
                ("filled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "pickup_status",
                    models.CharField(
                        choices=[
                            ("pending", "Oczekuje"),
                            ("confirmed", "Potwierdzony"),
                            ("declined", "Odmowa"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("sms_count", models.PositiveIntegerField(default=0)),
                ("sms_last_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "offer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ui.shipmentquoteoffer",
                    ),
                ),
                (
                    "shipment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver",
                        to="ui.shipment",
                    ),
                ),
            ],
        ),
    ]
