# Generated by Django 5.2.15 on 2026-06-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0038_shipmentquoteoffer_selected_driverassignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipmentquoteoffer",
            name="sender_email",
            field=models.CharField(blank=True, max_length=190),
        ),
        migrations.AddField(
            model_name="shipmentquoteoffer",
            name="sender_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Robocze"),
                    ("confirmed", "Zatwierdzone"),
                    ("sent", "Wysłane"),
                    ("cancelled", "Anulowane"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
