# Generated by Django 5.2.15 on 2026-06-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0039_shipmentquoteoffer_sender_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quoterecipient",
            name="is_warehouse",
            field=models.BooleanField(default=False, verbose_name="Magazyn"),
        ),
    ]
