# Generated by Django 5.2.15 on 2026-06-19 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0040_quoterecipient_is_warehouse"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HUQualityIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "issue_type",
                    models.CharField(
                        choices=[
                            ("wrong_assortment", "Błędny asortyment"),
                            ("wrong_batch", "Błędna seria"),
                            ("ajm_conversion", "Błąd przelicznika AJM"),
                            ("wrong_expiry", "Błędna data ważności"),
                            ("damaged", "Uszkodzony towar"),
                            ("bad_placement", "Nieprawidłowe ułożenie"),
                            ("foreign_item", "Obcy / nadmiarowy towar"),
                        ],
                        max_length=24,
                        verbose_name="Typ",
                    ),
                ),
                (
                    "ref_code",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="REF (obcy towar)"
                    ),
                ),
                ("qty", models.FloatField(blank=True, null=True, verbose_name="Ilość")),
                (
                    "note",
                    models.CharField(blank=True, max_length=300, verbose_name="Opis"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Otwarte"), ("closed", "Zamknięte")],
                        default="open",
                        max_length=8,
                    ),
                ),
                (
                    "resolution_note",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Rozwiązanie"
                    ),
                ),
                ("raised_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="closed_quality_issues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_issues",
                        to="ui.handlingunit",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_issues",
                        to="ui.handlingunititem",
                    ),
                ),
                (
                    "raised_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="raised_quality_issues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-raised_at"],
            },
        ),
    ]
