# Generated by Django 5.2.15 on 2026-06-19 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0041_huqualityissue"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="handlingunit",
            name="picker",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=80,
                verbose_name="Picker (kompletujący)",
            ),
        ),
        migrations.CreateModel(
            name="HUControlAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_recheck", models.BooleanField(default=False)),
                ("counted_qty", models.FloatField(blank=True, null=True)),
                ("counted_unit", models.CharField(blank=True, max_length=20)),
                ("exp_base_qty", models.FloatField(default=0)),
                ("exp_base_unit", models.CharField(blank=True, max_length=20)),
                ("exp_alt_qty", models.FloatField(default=0)),
                ("exp_alt_unit", models.CharField(blank=True, max_length=20)),
                ("result", models.CharField(blank=True, max_length=8)),
                ("error_flags", models.JSONField(blank=True, default=dict)),
                (
                    "seconds_since_prev",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Czas od poprzedniej pozycji [s]",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "controller",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hu_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="control_attempts",
                        to="ui.handlingunit",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="control_attempts",
                        to="ui.handlingunititem",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
