# Generated by Django 5.2.15 on 2026-06-19 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0042_handlingunit_picker_hucontrolattempt"),
    ]

    operations = [
        migrations.AddField(
            model_name="huqualityissue",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="quality/%Y/%m/",
                verbose_name="Zdjęcie",
            ),
        ),
    ]
