# Generated by Django 5.2.15 on 2026-06-19 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0043_huqualityissue_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="driverassignment",
            name="driver_language",
            field=models.CharField(
                default="pl", max_length=20, verbose_name="Język komunikacji"
            ),
        ),
        migrations.AddField(
            model_name="driverassignment",
            name="truck_eta",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Szac. godz. podstawienia auta"
            ),
        ),
        migrations.AddField(
            model_name="shipmentquoteoffer",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="quotes/%Y/%m/",
                verbose_name="Załącznik (oferta/dokument)",
            ),
        ),
    ]
