# Generated by Django 5.2.15 on 2026-06-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0044_driverassignment_driver_language_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "leaders",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        verbose_name="Liderzy magazynu (kontakty)",
                    ),
                ),
                (
                    "site_map",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="site/",
                        verbose_name="Mapka obiektu",
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        blank=True, verbose_name="Instrukcja poruszania się na obiekcie"
                    ),
                ),
            ],
            options={
                "verbose_name": "Informacje o obiekcie (dla kierowcy)",
                "verbose_name_plural": "Informacje o obiekcie (dla kierowcy)",
            },
        ),
        migrations.AddField(
            model_name="shipment",
            name="ramp",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Numer rampy"
            ),
        ),
    ]
