# Generated by Django 5.2.15 on 2026-06-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0045_siteinfo_shipment_ramp"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="is_stock",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Kontener stanu (import HU)"
            ),
        ),
    ]
