# Generated by Django 5.2.15 on 2026-06-19 08:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0046_shipment_is_stock"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nazwa / firma"),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=40,
                        verbose_name="Kod klienta",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("customer", "Klient"), ("consignee", "Odbiorca")],
                        default="customer",
                        max_length=10,
                        verbose_name="Typ",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=2, verbose_name="Kraj (ISO)"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="Miasto"),
                ),
                (
                    "postal",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Kod pocztowy"
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-mail kontaktowy"
                    ),
                ),
                (
                    "max_pallet_height_cm",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Jeśli ustawione, kalkulator nie zaproponuje wyższej palety dla tego klienta.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(50),
                            django.core.validators.MaxValueValidator(280),
                        ],
                        verbose_name="Maks. wysokość palety [cm]",
                    ),
                ),
                (
                    "max_pallet_weight_kg",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Maks. waga palety [kg]"
                    ),
                ),
                (
                    "requires_fumigated_pallet",
                    models.BooleanField(
                        default=False,
                        verbose_name="Wymaga palety fumigowanej (IPPC/ISPM 15)",
                    ),
                ),
                (
                    "pallet_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Dowolna"),
                            ("euro", "Euro 120×80"),
                            ("industrial", "Przemysłowa 120×100"),
                            ("disposable", "Jednorazowa"),
                        ],
                        default="",
                        max_length=12,
                        verbose_name="Wymagany typ palety",
                    ),
                ),
                (
                    "requirements_notes",
                    models.TextField(blank=True, verbose_name="Dodatkowe wymagania"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktywny"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="shipment",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shipments",
                to="ui.customer",
                verbose_name="Klient / odbiorca",
            ),
        ),
    ]
