# Generated by Django 5.2.15 on 2026-06-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0047_customer_shipment_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="phone",
            field=models.CharField(blank=True, max_length=40, verbose_name="Telefon"),
        ),
        migrations.AddField(
            model_name="customer",
            name="street",
            field=models.CharField(blank=True, max_length=200, verbose_name="Ulica"),
        ),
    ]
