# Generated by Django 5.2.15 on 2026-06-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0048_customer_phone_customer_street"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="selected_pallet_height_cm",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Wybrana wysokość palety [cm]"
            ),
        ),
    ]
