# Generated by Django 5.2.15 on 2026-06-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0049_shipment_selected_pallet_height_cm"),
    ]

    operations = [
        migrations.CreateModel(
            name="ControlledWarehouseType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        unique=True,
                        verbose_name="Typ magazynu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kontrolowany typ magazynu",
                "verbose_name_plural": "Kontrolowane typy magazynu",
                "ordering": ["code"],
            },
        ),
    ]
