# Generated by Django 5.2.15 on 2026-06-20 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0050_controlledwarehousetype"),
        ("ui", "0050_flag_legacy_stock_containers"),
    ]

    operations = []
