# Generated by Django 5.2.15 on 2026-06-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("ui", "0051_merge_20260620_1526"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        help_text="Stały identyfikator, np. 'jazz', 'beat', 'takt'.",
                        max_length=40,
                        unique=True,
                        verbose_name="Klucz (slug)",
                    ),
                ),
                ("name", models.CharField(max_length=60, verbose_name="Nazwa")),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, verbose_name="Opis"),
                ),
                (
                    "base_url",
                    models.URLField(
                        help_text="np. https://jazz.example.com",
                        verbose_name="Adres aplikacji",
                    ),
                ),
                (
                    "sso_path",
                    models.CharField(
                        default="/sso",
                        help_text="Endpoint w aplikacji, który przyjmuje token (?token=…).",
                        max_length=120,
                        verbose_name="Ścieżka SSO",
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#6366f1", max_length=7, verbose_name="Kolor kafelka"
                    ),
                ),
                (
                    "icon",
                    models.CharField(default="🎵", max_length=8, verbose_name="Ikona"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktywna"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Kolejność"),
                ),
                (
                    "allowed_groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Puste = każdy zalogowany użytkownik.",
                        related_name="platform_apps",
                        to="auth.group",
                        verbose_name="Role z dostępem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aplikacja platformy",
                "verbose_name_plural": "Aplikacje platformy",
                "ordering": ["order", "name"],
            },
        ),
    ]
