# Generated by Django 5.2.15 on 2026-06-20 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0052_platformapp"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PlatformApp",
        ),
    ]
