# Generated by Django 5.2.15 on 2026-06-20 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0053_delete_platformapp"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Ostrzeżenie"),
                            ("error", "Błąd"),
                        ],
                        default="warning",
                        max_length=8,
                    ),
                ),
                ("title", models.CharField(max_length=160, verbose_name="Tytuł")),
                (
                    "body",
                    models.CharField(blank=True, max_length=400, verbose_name="Treść"),
                ),
                (
                    "url",
                    models.CharField(blank=True, max_length=300, verbose_name="Link"),
                ),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Powiadomienie",
                "verbose_name_plural": "Powiadomienia",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Tytuł")),
                ("description", models.TextField(blank=True, verbose_name="Opis")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("manual", "Ręczne"),
                            ("stock_discrepancy", "Niezgodność stocku"),
                        ],
                        default="manual",
                        max_length=24,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Niski"),
                            ("normal", "Normalny"),
                            ("high", "Wysoki"),
                        ],
                        default="normal",
                        max_length=8,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "Do zrobienia"),
                            ("in_progress", "W toku"),
                            ("done", "Zrobione"),
                        ],
                        db_index=True,
                        default="todo",
                        max_length=12,
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="Termin"),
                ),
                (
                    "source_ref",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Źródło (np. HU)"
                    ),
                ),
                ("url", models.CharField(blank=True, max_length=300)),
                (
                    "dedup_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=120,
                        verbose_name="Klucz deduplikacji",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Przypisane do",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Zadanie",
                "verbose_name_plural": "Zadania",
                "ordering": ["status", "-priority", "-created_at"],
            },
        ),
    ]
