# Generated by Django 5.2.15 on 2026-06-20 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0054_notification_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="overdue_notified",
            field=models.BooleanField(default=False),
        ),
    ]
