# Generated by Django 5.2.15 on 2026-06-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0057_taskchecklistitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="overdue_notified",
        ),
        migrations.AddField(
            model_name="task",
            name="overdue_last_reminded",
            field=models.DateField(blank=True, null=True),
        ),
    ]
