# Generated by Django 5.2.15 on 2026-06-20 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0058_remove_task_overdue_notified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="related_hu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="ui.handlingunit",
                verbose_name="Powiązany HU",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="related_location",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Powiązana lokalizacja"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="related_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="ui.product",
                verbose_name="Powiązany produkt",
            ),
        ),
    ]
