# Generated by Django 5.2.15 on 2026-06-20 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0059_task_related_hu_task_related_location_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="category",
            field=models.CharField(
                choices=[
                    ("manual", "Ręczne"),
                    ("stock_discrepancy", "Niezgodność stocku"),
                    ("recurring", "Cykliczne"),
                ],
                default="manual",
                max_length=24,
            ),
        ),
        migrations.CreateModel(
            name="RecurringTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Tytuł")),
                ("description", models.TextField(blank=True, verbose_name="Opis")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Niski"),
                            ("normal", "Normalny"),
                            ("high", "Wysoki"),
                        ],
                        default="normal",
                        max_length=8,
                    ),
                ),
                (
                    "interval",
                    models.CharField(
                        choices=[
                            ("daily", "Codziennie"),
                            ("weekly", "Co tydzień"),
                            ("monthly", "Co miesiąc"),
                        ],
                        default="weekly",
                        max_length=8,
                        verbose_name="Częstotliwość",
                    ),
                ),
                ("next_run", models.DateField(verbose_name="Następne uruchomienie")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktywne"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recurring_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Przypisane do",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zadanie cykliczne",
                "verbose_name_plural": "Zadania cykliczne",
                "ordering": ["next_run"],
            },
        ),
    ]
