# Generated by Django 5.2.15 on 2026-06-21 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0061_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipmentquoteoffer",
            name="fuel_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name="Dopłata paliwowa [%]",
            ),
        ),
        migrations.AddField(
            model_name="shipmentquoteoffer",
            name="surcharge_fixed",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Dopłata stała"
            ),
        ),
        migrations.AddField(
            model_name="shipmentquoteoffer",
            name="surcharge_note",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Opis dopłat"
            ),
        ),
    ]
