# Generated by Django 5.2.15 on 2026-06-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0062_shipmentquoteoffer_fuel_pct_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PowerBIToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cache",
                    models.TextField(blank=True, verbose_name="Cache tokenu (MSAL)"),
                ),
                (
                    "account",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Połączone konto"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Token Power BI (logowanie użytkownika)",
                "verbose_name_plural": "Token Power BI (logowanie użytkownika)",
            },
        ),
    ]
