# Generated by Django 5.2.15 on 2026-06-21 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0064_alter_shipment_stowage_efficiency_pct"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StockMovement",
        ),
    ]
