# Generated by Django 5.2.15 on 2026-06-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0065_delete_stockmovement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="huqualityissue",
            name="issue_type",
            field=models.CharField(
                choices=[
                    ("missing", "Brak towaru"),
                    ("wrong_assortment", "Błędny asortyment / zły indeks"),
                    ("damaged", "Uszkodzony towar"),
                    ("wrong_batch", "Błędna seria"),
                    ("ajm_conversion", "Błąd przelicznika AJM"),
                    ("wrong_expiry", "Błędna data ważności"),
                    ("bad_placement", "Nieprawidłowe ułożenie"),
                    ("foreign_item", "Obcy / nadmiarowy towar"),
                ],
                max_length=24,
                verbose_name="Typ",
            ),
        ),
    ]
