# Generated by Django 5.2.15 on 2026-06-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0066_alter_huqualityissue_issue_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="handlingunit",
            name="is_priority",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Priorytet (rekontrola)"
            ),
        ),
    ]
