# Generated by Django 5.2.15 on 2026-06-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0068_alter_huqualityissue_issue_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproduct",
            name="max_stack_layers",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Maks. warstw na palecie (0 = bez limitu)"
            ),
        ),
        migrations.AddField(
            model_name="historicalproduct",
            name="stackable",
            field=models.BooleanField(default=True, verbose_name="Można piętrować"),
        ),
        migrations.AddField(
            model_name="product",
            name="max_stack_layers",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Maks. warstw na palecie (0 = bez limitu)"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="stackable",
            field=models.BooleanField(default=True, verbose_name="Można piętrować"),
        ),
    ]
