# Generated by Django 5.2.15 on 2026-06-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0069_historicalproduct_max_stack_layers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="client_requirements",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="Wymagania klienta"
            ),
        ),
    ]
