# Generated by Django 5.2.15 on 2026-06-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0070_shipment_client_requirements"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="actual_hu_count",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Liczba jednostek obsługi z dokumentu dostawy SAP — faktyczna liczba palet, jaka wyszła. Gdy podana, wycena kotwiczy się na niej.",
                null=True,
                verbose_name="Rzeczywista liczba HU (SAP)",
            ),
        ),
    ]
