# Generated by Django 5.2.15 on 2026-06-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0071_shipment_actual_hu_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="warehouse_pallets",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Liczba palet uzgodniona z magazynem — kotwiczy wycenę i wysyłkę do spedycji.",
                null=True,
                verbose_name="Palet potwierdzonych przez magazyn",
            ),
        ),
        migrations.AddField(
            model_name="warehousereadiness",
            name="asked_pallets",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Palet w zapytaniu"
            ),
        ),
        migrations.AddField(
            model_name="warehousereadiness",
            name="confirmed_pallets",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Palet potwierdzonych"
            ),
        ),
        migrations.AddField(
            model_name="warehousereadiness",
            name="ready_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Najszybszy termin gotowości"
            ),
        ),
        migrations.AddField(
            model_name="warehousereadiness",
            name="suggested_pallets",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Palet proponowanych przez magazyn"
            ),
        ),
    ]
