# Generated by Django 5.2.15 on 2026-06-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0072_shipment_warehouse_pallets_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="anchor_note",
            field=models.CharField(
                blank=True,
                max_length=300,
                verbose_name="Komentarz do liczby palet (rozjazd danych)",
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="transport_modes",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Typy wysyłki (pojazdy)"
            ),
        ),
    ]
