# Generated by Django 5.2.15 on 2026-06-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0073_shipment_anchor_note_shipment_transport_modes"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="load_mode",
            field=models.CharField(
                choices=[("pallets", "Na paletach"), ("loose", "Bez palet (luzem)")],
                default="pallets",
                max_length=10,
                verbose_name="Tryb załadunku",
            ),
        ),
    ]
