# Generated by Django 5.2.15 on 2026-06-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0074_shipment_load_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="client_eta",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Przybliżona data dostawy do klienta",
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="client_loaded_notified_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Powiadomiono klienta o załadunku"
            ),
        ),
    ]
