# Generated by Django 5.2.15 on 2026-06-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0075_shipment_client_eta_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="delivery_hours",
            field=models.CharField(
                blank=True,
                help_text="np. „pn–pt 08:00–14:00, awizacja 24 h”.",
                max_length=120,
                verbose_name="Okna dostaw",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="requires_adr",
            field=models.BooleanField(default=False, verbose_name="Wymaga ADR"),
        ),
        migrations.AddField(
            model_name="customer",
            name="temp_control",
            field=models.CharField(
                blank=True,
                help_text="np. „+2…+8°C” — puste = brak wymogu chłodni.",
                max_length=40,
                verbose_name="Wymagana temperatura",
            ),
        ),
    ]
