# Generated by Django 5.2.15 on 2026-06-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0076_customer_delivery_hours_customer_requires_adr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="ready_notified_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Powiadomiono o gotowości wszystkich palet",
            ),
        ),
    ]
