# Generated by Django 5.2.15 on 2026-06-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0077_shipment_ready_notified_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpalletizationinstruction",
            name="unit_volume_m3",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Objętość 1 szt/OP [m³] (z MARM)"
            ),
        ),
        migrations.AddField(
            model_name="palletizationinstruction",
            name="unit_volume_m3",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Objętość 1 szt/OP [m³] (z MARM)"
            ),
        ),
    ]
