# Generated by Django 5.2.15 on 2026-06-30 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0078_historicalpalletizationinstruction_unit_volume_m3_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ["status", "-created_at"],
                "verbose_name": "Zadanie",
                "verbose_name_plural": "Zadania",
            },
        ),
    ]
