# Generated by Django 5.2.15 on 2026-07-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0079_alter_task_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "verbose_name": "Profil użytkownika",
                "verbose_name_plural": "Profile użytkowników",
            },
        ),
        migrations.AddField(
            model_name="userprofile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email_notifications",
            field=models.BooleanField(
                default=True, verbose_name="Powiadomienia e-mail"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
