# Generated by Django 5.2.15 on 2026-07-08 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0081_backfill_user_profiles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="handlingunit",
            name="client_reqs_confirmed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Wymagania klienta potwierdzone"
            ),
        ),
        migrations.AddField(
            model_name="handlingunit",
            name="client_reqs_confirmed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hu_reqs_confirmed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="ControllerZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Typ magazynu"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="control_zones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Strefa kontroli użytkownika",
                "verbose_name_plural": "Strefy kontroli (użytkownik × typ magazynu)",
                "ordering": ["user_id", "code"],
                "unique_together": {("user", "code")},
            },
        ),
    ]
