# Generated by Django 5.2.15 on 2026-07-11 09:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0082_handlingunit_client_reqs_confirmed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="wz_copies",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Ile wydrukowanych kopii dokumentu WZ wymaga klient (np. 2, 3, 4).",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(9),
                ],
                verbose_name="Liczba kopii WZ",
            ),
        ),
        migrations.AlterField(
            model_name="huqualityissue",
            name="issue_type",
            field=models.CharField(
                choices=[
                    ("wrong_assortment", "Błędny asortyment / zły indeks"),
                    ("damaged", "Uszkodzony towar"),
                    ("wrong_batch", "Błędna seria"),
                    ("ajm_conversion", "Błąd przelicznika AJM"),
                    ("wrong_expiry", "Błędna data ważności"),
                    ("bad_placement", "Nieprawidłowe ułożenie"),
                    ("wrong_label", "Zła / brak etykiety"),
                    ("missing_document", "Brak dokumentu / certyfikatu"),
                    ("foreign_item", "Obcy / nadmiarowy towar"),
                ],
                max_length=24,
                verbose_name="Typ",
            ),
        ),
    ]
