# Generated by Django 5.2.15 on 2026-07-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0083_customer_wz_copies_alter_huqualityissue_issue_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="handlingunit",
            name="control_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
