# Generated by Django 5.2.15 on 2026-07-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0085_hustatusevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="handlingunit",
            name="last_seen_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
