# Generated by Django 5.2.15 on 2026-07-17 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0086_handlingunit_last_seen_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HUPrintProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, verbose_name="Projekt")),
                (
                    "label_text",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Duży tekst na etykiecie; puste = tylko numer (np. Projekt Alfa).",
                        max_length=40,
                        verbose_name="Nazwa na etykiecie",
                    ),
                ),
                (
                    "next_number",
                    models.BigIntegerField(
                        default=1,
                        help_text="Kolejny numer do wydruku (edytowalny start).",
                        verbose_name="Następny numer",
                    ),
                ),
                (
                    "digits",
                    models.PositiveSmallIntegerField(
                        default=9, verbose_name="Liczba cyfr (zero-padding)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktywny"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Projekt wydruku HU",
                "verbose_name_plural": "Projekty wydruku HU",
                "ordering": ["next_number", "name"],
            },
        ),
        migrations.CreateModel(
            name="HUPrintRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="Ilość etykiet")),
                ("from_number", models.BigIntegerField(verbose_name="Od numeru")),
                ("to_number", models.BigIntegerField(verbose_name="Do numeru")),
                (
                    "symbology",
                    models.CharField(
                        default="code128", max_length=10, verbose_name="Symbolika"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="ui.huprintproject",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hu_print_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Przebieg wydruku HU",
                "verbose_name_plural": "Przebiegi wydruku HU",
                "ordering": ["-created_at"],
            },
        ),
    ]
