# Generated by Django 5.2.15 on 2026-07-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0088_seed_hu_print_projects"),
    ]

    operations = [
        migrations.AddField(
            model_name="huprintrun",
            name="username",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="Użytkownik"
            ),
        ),
    ]
