# Generated by Django 5.2.15 on 2026-07-17 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0091_project_start_numbers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserModuleAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("module_key", models.CharField(max_length=40, verbose_name="Moduł")),
                ("allowed", models.BooleanField(verbose_name="Dostęp")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_access",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dostęp użytkownika do modułu",
                "verbose_name_plural": "Dostępy użytkowników do modułów",
                "unique_together": {("user", "module_key")},
            },
        ),
    ]
