# Generated by Django 5.2.15 on 2026-07-18 05:25

from django.db import migrations, models


def _backfill_codes(apps, schema_editor):
    """Copy each existing task's FK product code into the new business-key field, so the
    code becomes the source of truth before the FK is eventually dropped."""
    Task = apps.get_model("ui", "Task")
    for task in Task.objects.filter(related_product__isnull=False).select_related("related_product"):
        code = (task.related_product.code or "")[:50]
        if code and task.related_product_code != code:
            task.related_product_code = code
            task.save(update_fields=["related_product_code"])


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0092_usermoduleaccess"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="related_product_code",
            field=models.CharField(
                blank=True,
                default="",
                max_length=50,
                verbose_name="Kod powiązanego produktu",
            ),
        ),
        migrations.RunPython(_backfill_codes, migrations.RunPython.noop),
    ]
