# Generated by Django 5.2.15 on 2026-07-18 06:27

from django.db import migrations, models
from django.db.models import OuterRef, Subquery


def _backfill_codes(apps, schema_editor):
    """Copy each line's FK product code into the new business-key field (single UPDATE
    with a correlated subquery — shipment lines can number tens of thousands)."""
    ShipmentLine = apps.get_model("ui", "ShipmentLine")
    Product = apps.get_model("ui", "Product")
    ShipmentLine.objects.update(
        product_code=Subquery(Product.objects.filter(pk=OuterRef("product_id")).values("code")[:1])
    )


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0093_task_related_product_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipmentline",
            name="product_code",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Kod produktu"
            ),
        ),
        migrations.RunPython(_backfill_codes, migrations.RunPython.noop),
    ]
