# Generated by Django 5.2.16 on 2026-07-26 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0094_shipmentline_product_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ZariaModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Identyfikator modelu u dostawcy, np. claude-sonnet-4-5",
                        max_length=60,
                        unique=True,
                        verbose_name="Identyfikator modelu",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(max_length=100, verbose_name="Nazwa wyświetlana"),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("anthropic", "Anthropic"),
                            ("openai", "OpenAI"),
                            ("azure_openai", "Azure OpenAI"),
                        ],
                        max_length=20,
                        verbose_name="Dostawca",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktywny"),
                ),
                (
                    "price_input_per_1k",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        max_digits=10,
                        verbose_name="Cena za 1k tokenów wejściowych (PLN)",
                    ),
                ),
                (
                    "price_output_per_1k",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        max_digits=10,
                        verbose_name="Cena za 1k tokenów wyjściowych (PLN)",
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(
                        blank=True, verbose_name="Prompt systemowy (nadpisuje globalny)"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Kolejność"
                    ),
                ),
            ],
            options={
                "verbose_name": "Model ZARIA",
                "verbose_name_plural": "Modele ZARIA",
                "ordering": ["sort_order", "display_name"],
            },
        ),
        migrations.AlterField(
            model_name="task",
            name="category",
            field=models.CharField(
                choices=[
                    ("manual", "Ręczne"),
                    ("stock_discrepancy", "Niezgodność stocku"),
                    ("recurring", "Cykliczne"),
                    ("zaria_budget", "Budżet ZARIA"),
                ],
                default="manual",
                max_length=24,
            ),
        ),
        migrations.CreateModel(
            name="ZariaConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=200, verbose_name="Tytuł"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "accepted_privacy_notice_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Akceptacja RODO"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zaria_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversations",
                        to="ui.zariamodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Konwersacja ZARIA",
                "verbose_name_plural": "Konwersacje ZARIA",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ZariaMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "Użytkownik"),
                            ("assistant", "Asystent"),
                            ("system", "System"),
                        ],
                        max_length=10,
                    ),
                ),
                ("content", models.TextField()),
                ("prompt_tokens", models.PositiveIntegerField(default=0)),
                ("completion_tokens", models.PositiveIntegerField(default=0)),
                (
                    "cost_pln",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                ("latency_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("error", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="ui.zariaconversation",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="ui.zariamodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wiadomość ZARIA",
                "verbose_name_plural": "Wiadomości ZARIA",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ZariaConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(
                        blank=True, verbose_name="Globalny prompt systemowy"
                    ),
                ),
                (
                    "monthly_budget_pln",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Globalny miesięczny budżet (PLN, 0=brak limitu)",
                    ),
                ),
                (
                    "per_user_monthly_budget_pln",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Domyślny miesięczny budżet na użytkownika (PLN, 0=brak limitu)",
                    ),
                ),
                (
                    "rate_limit_per_minute",
                    models.PositiveSmallIntegerField(
                        default=10, verbose_name="Limit wiadomości/minutę"
                    ),
                ),
                (
                    "rate_limit_per_day",
                    models.PositiveIntegerField(
                        default=200, verbose_name="Limit wiadomości/dzień"
                    ),
                ),
                (
                    "hard_block_over_budget",
                    models.BooleanField(
                        default=False,
                        verbose_name="Blokuj wysyłkę po przekroczeniu budżetu (inaczej: tylko ostrzeżenie)",
                    ),
                ),
                (
                    "rodo_notice",
                    models.TextField(blank=True, verbose_name="Treść komunikatu RODO"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "default_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="ui.zariamodel",
                        verbose_name="Model domyślny",
                    ),
                ),
            ],
            options={
                "verbose_name": "Konfiguracja ZARIA (globalna)",
                "verbose_name_plural": "Konfiguracja ZARIA (globalna)",
            },
        ),
        migrations.CreateModel(
            name="ZariaUserBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monthly_budget_pln",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Miesięczny budżet (PLN)",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zaria_budget",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Budżet ZARIA użytkownika",
                "verbose_name_plural": "Budżety ZARIA użytkowników",
            },
        ),
        migrations.CreateModel(
            name="ZariaModelRoleAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_name", models.CharField(max_length=60, verbose_name="Rola")),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_access",
                        to="ui.zariamodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dostęp roli do modelu ZARIA",
                "verbose_name_plural": "Dostępy ról do modeli ZARIA",
                "unique_together": {("model", "group_name")},
            },
        ),
        migrations.CreateModel(
            name="ZariaUserModelAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("allowed", models.BooleanField(verbose_name="Dostęp")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_overrides",
                        to="ui.zariamodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zaria_model_access",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dostęp użytkownika do modelu ZARIA",
                "verbose_name_plural": "Dostępy użytkowników do modeli ZARIA",
                "unique_together": {("user", "model")},
            },
        ),
    ]
