# Generated by Django 5.2.16 on 2026-07-27 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0095_zariamodel_alter_task_category_zariaconversation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Nazwa')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('lang', models.CharField(choices=[('pl', 'Polski'), ('en', 'English')], default='pl', max_length=2, verbose_name='Język')),
                ('theme', models.CharField(choices=[('light', 'Jasny'), ('dark', 'Ciemny'), ('auto', 'Auto')], default='light', max_length=6, verbose_name='Motyw')),
                ('status', models.CharField(choices=[('draft', 'Szkic'), ('published', 'Opublikowany')], default='draft', max_length=10, verbose_name='Status')),
                ('doc', models.JSONField(blank=True, default=dict, verbose_name='Treść mapy (sceny)')),
                ('public', models.BooleanField(default=False, verbose_name='Link publiczny (bez logowania)')),
                ('slug', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='Token linku')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animaflow_maps', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('editors', models.ManyToManyField(blank=True, related_name='animaflow_editable', to=settings.AUTH_USER_MODEL, verbose_name='Edytorzy')),
            ],
            options={
                'verbose_name': 'Mapa procesu (AnimaFlow)',
                'verbose_name_plural': 'Mapy procesów (AnimaFlow)',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessMapVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.JSONField(default=dict)),
                ('label', models.CharField(blank=True, max_length=120, verbose_name='Etykieta wersji')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('process_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='ui.processmap')),
            ],
            options={
                'verbose_name': 'Wersja mapy procesu',
                'verbose_name_plural': 'Wersje map procesów',
                'ordering': ['-created_at'],
            },
        ),
    ]
