# Generated by Django 5.2.16 on 2026-07-27 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0096_processmap_processmapversion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZariaRoleTokenBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=60, unique=True, verbose_name='Rola')),
                ('monthly_tokens', models.PositiveIntegerField(verbose_name='Miesięczny limit tokenów (0=brak)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Limit tokenów ZARIA per rola',
                'verbose_name_plural': 'Limity tokenów ZARIA per rola',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, max_length=80, verbose_name='Dział'),
        ),
        migrations.AddField(
            model_name='zariaconfig',
            name='default_monthly_token_budget',
            field=models.PositiveIntegerField(default=500000, verbose_name='Domyślny miesięczny limit tokenów / użytkownika (0=brak)'),
        ),
        migrations.AddField(
            model_name='zariaconfig',
            name='max_message_chars',
            field=models.PositiveIntegerField(default=8000, verbose_name='Maks. długość wiadomości (znaki)'),
        ),
        migrations.AddField(
            model_name='zariaconfig',
            name='max_tokens',
            field=models.PositiveIntegerField(default=1000, verbose_name='Maks. tokenów odpowiedzi'),
        ),
        migrations.AlterField(
            model_name='zariaconfig',
            name='rate_limit_per_minute',
            field=models.PositiveSmallIntegerField(default=20, verbose_name='Limit wiadomości/minutę'),
        ),
        migrations.CreateModel(
            name='ZariaAdminAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=60, verbose_name='Zdarzenie')),
                ('detail', models.CharField(blank=True, max_length=400, verbose_name='Szczegóły')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audyt ZARIA (admin)',
                'verbose_name_plural': 'Audyt ZARIA (admin)',
                'ordering': ['-created_at'],
            },
        ),
    ]
