# Generated by Django 5.2.16 on 2026-07-27 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0097_zariaroletokenbudget_userprofile_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=60, verbose_name='Zdarzenie')),
                ('detail', models.CharField(blank=True, max_length=400, verbose_name='Szczegóły')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Dotyczy użytkownika')),
            ],
            options={
                'verbose_name': 'Audyt dostępu',
                'verbose_name_plural': 'Audyt dostępu',
                'ordering': ['-created_at'],
            },
        ),
    ]
