# Generated by Django 5.2.16 on 2026-07-27 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0098_accessaudit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zariaconfig',
            name='default_monthly_token_budget',
            field=models.PositiveIntegerField(default=800000, verbose_name='Domyślny miesięczny limit tokenów / użytkownika (0=brak)'),
        ),
        migrations.AlterField(
            model_name='zariaconfig',
            name='hard_block_over_budget',
            field=models.BooleanField(default=True, verbose_name='Blokuj wysyłkę po przekroczeniu budżetu (inaczej: tylko ostrzeżenie)'),
        ),
    ]
