# Generated by Django 5.2.16 on 2026-07-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0099_alter_zariaconfig_default_monthly_token_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zariaconfig',
            name='hard_block_fraction',
            field=models.PositiveSmallIntegerField(default=97, verbose_name='Próg twardej blokady globalnej (% capu, 1–100)'),
        ),
    ]
