# Generated by Django 5.2.16 on 2026-07-28 10:43

from django.conf import settings
from django.db import migrations, models
from django.db.models import Count


def backfill_verified_at(apps, schema_editor):
    """Przed CheckConstraint ok⇒verified_at: uzupełnij brakujące znaczniki na istniejących
    'ok' HU (control_started_at → created_at), żeby constraint nie padł na starych danych."""
    HandlingUnit = apps.get_model("ui", "HandlingUnit")
    for hu in HandlingUnit.objects.filter(status="ok", verified_at__isnull=True):
        hu.verified_at = hu.control_started_at or hu.created_at
        hu.save(update_fields=["verified_at"])


def close_duplicate_open_issues(apps, schema_editor):
    """Przed partial-unique huqi_open_dedup: zamknij duplikaty OTWARTYCH issue na tej samej
    (hu, item, typ) — zostaw najstarszy (min id), resztę oznacz jako zamknięte."""
    from django.utils import timezone
    HUQualityIssue = apps.get_model("ui", "HUQualityIssue")
    dup_keys = (HUQualityIssue.objects.filter(status="open")
                .values("hu_id", "item_id", "issue_type")
                .annotate(n=Count("id")).filter(n__gt=1))
    for k in dup_keys:
        rows = list(HUQualityIssue.objects.filter(
            status="open", hu_id=k["hu_id"], item_id=k["item_id"],
            issue_type=k["issue_type"]).order_by("id"))
        for extra in rows[1:]:
            extra.status = "closed"
            extra.closed_at = timezone.now()
            extra.resolution_note = (extra.resolution_note
                                     or "Auto: scalony duplikat przy migracji 0100")
            extra.save(update_fields=["status", "closed_at", "resolution_note"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0099_alter_zariaconfig_default_monthly_token_budget_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hucontrolattempt',
            name='client_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='handlingunit',
            name='status',
            field=models.CharField(choices=[('planned', 'Zaplanowany'), ('in_control', 'W kontroli'), ('ok', 'Zgodny'), ('to_recheck', 'Do rekontroli'), ('escaped', 'Wyjechało bez kontroli')], default='planned', max_length=12, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='hustatusevent',
            name='from_status',
            field=models.CharField(blank=True, choices=[('planned', 'Zaplanowany'), ('in_control', 'W kontroli'), ('ok', 'Zgodny'), ('to_recheck', 'Do rekontroli'), ('escaped', 'Wyjechało bez kontroli')], max_length=12),
        ),
        migrations.AlterField(
            model_name='hustatusevent',
            name='to_status',
            field=models.CharField(choices=[('planned', 'Zaplanowany'), ('in_control', 'W kontroli'), ('ok', 'Zgodny'), ('to_recheck', 'Do rekontroli'), ('escaped', 'Wyjechało bez kontroli')], max_length=12),
        ),
        migrations.RunPython(backfill_verified_at, noop),
        migrations.AddConstraint(
            model_name='handlingunit',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'ok'), _negated=True), ('verified_at__isnull', False), _connector='OR'), name='hu_ok_requires_verified_at'),
        ),
        migrations.AddConstraint(
            model_name='hucontrolattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('client_id', ''), _negated=True), fields=('client_id',), name='huattempt_client_id_uniq'),
        ),
        migrations.RunPython(close_duplicate_open_issues, noop),
        migrations.AddConstraint(
            model_name='huqualityissue',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('hu', 'item', 'issue_type'), name='huqi_open_dedup'),
        ),
    ]
