# Generated by Django 5.2.16 on 2026-07-28 15:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0100_hucontrolattempt_client_id_alter_handlingunit_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='min_shelf_life_months',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Poniżej tej reszty ważności pozycja wymaga potwierdzenia przy kontroli.', null=True, validators=[django.core.validators.MaxValueValidator(60)], verbose_name='Min. ważność przy dostawie [mies.]'),
        ),
        migrations.AddField(
            model_name='handlingunit',
            name='short_dated_ack_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Krótki termin potwierdzony'),
        ),
        migrations.AddField(
            model_name='handlingunit',
            name='short_dated_ack_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hu_short_dated_ack', to=settings.AUTH_USER_MODEL),
        ),
    ]
