# Generated by Django 5.2.16 on 2026-07-29 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0101_customer_min_shelf_life_months_and_more'),
        ('ui', '0101_zaria_activate_cap'),
    ]

    operations = [
    ]
