# Generated by Django 5.2.16 on 2026-07-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0102_merge_20260729_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('manual', 'Ręczne'), ('stock_discrepancy', 'Niezgodność stocku'), ('recurring', 'Cykliczne'), ('zaria_budget', 'Budżet ZARIA'), ('hu_fix', 'Naprawcze (kontrola HU)'), ('hu_stale', 'HU zniknęła z importu')], default='manual', max_length=24),
        ),
    ]
