# Generated by Django 5.2.16 on 2026-07-30 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0103_alter_task_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zariamodel',
            name='provider',
            field=models.CharField(choices=[('anthropic', 'Anthropic'), ('openai', 'OpenAI'), ('azure_openai', 'Azure OpenAI'), ('ollama', 'Ollama (lokalny)')], max_length=20, verbose_name='Dostawca'),
        ),
    ]
