# Generated by Django 5.2.16 on 2026-07-30 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0105_handlingunit_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='label_extra_text',
            field=models.CharField(blank=True, help_text='Np. numer umowy — drukowany na każdej etykiecie tego klienta.', max_length=200, verbose_name='Stały tekst na etykiecie'),
        ),
        migrations.AddField(
            model_name='customer',
            name='label_language',
            field=models.CharField(choices=[('pl', 'Polski'), ('en', 'English'), ('de', 'Deutsch')], default='pl', max_length=2, verbose_name='Język etykiety'),
        ),
        migrations.AddField(
            model_name='customer',
            name='label_show_lot_exp',
            field=models.BooleanField(default=True, verbose_name='Etykieta: LOT i termin ważności'),
        ),
        migrations.AddField(
            model_name='customer',
            name='label_show_requirements',
            field=models.BooleanField(default=True, verbose_name='Etykieta: notatki wymagań'),
        ),
        migrations.AddField(
            model_name='customer',
            name='requires_logistics_label',
            field=models.BooleanField(default=False, help_text='Po kontroli HU kontroler może wydrukować etykietę z zawartością palety.', verbose_name='Wymaga etykiety logistycznej'),
        ),
    ]
