# Generated by Django 5.2.16 on 2026-08-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0107_hu_code_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerbitoken',
            name='last_error',
            field=models.TextField(blank=True, verbose_name='Ostatni błąd'),
        ),
        migrations.AddField(
            model_name='powerbitoken',
            name='last_error_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data ostatniego błędu'),
        ),
    ]
