# Generated by Django 5.2.16 on 2026-08-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0108_powerbitoken_last_error_powerbitoken_last_error_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='zariaconfig',
            name='rag_enabled',
            field=models.BooleanField(default=True, verbose_name='RAG: wzbogacaj odpowiedzi danymi GROOVE (tylko odczyt)'),
        ),
    ]
