# Generated by Django 5.2.16 on 2026-08-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0109_zariaconfig_rag_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_vip',
            field=models.BooleanField(default=False, verbose_name='Klient VIP'),
        ),
        migrations.AddField(
            model_name='customer',
            name='kunnr',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Kod SAP (KUNNR)'),
        ),
        migrations.AddField(
            model_name='handlingunit',
            name='height_cm',
            field=models.FloatField(blank=True, null=True, verbose_name='Wysokość [cm]'),
        ),
        migrations.AddField(
            model_name='handlingunit',
            name='is_completed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Skompletowana (picking)'),
        ),
        migrations.AddField(
            model_name='handlingunit',
            name='length_cm',
            field=models.FloatField(blank=True, null=True, verbose_name='Długość [cm]'),
        ),
        migrations.AddField(
            model_name='handlingunit',
            name='weight_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='Waga [kg]'),
        ),
        migrations.AddField(
            model_name='handlingunit',
            name='width_cm',
            field=models.FloatField(blank=True, null=True, verbose_name='Szerokość [cm]'),
        ),
        migrations.AddField(
            model_name='handlingunititem',
            name='md_exception',
            field=models.BooleanField(default=False, verbose_name='Wyjątek master daty'),
        ),
        migrations.AddField(
            model_name='handlingunititem',
            name='md_exception_note',
            field=models.CharField(blank=True, max_length=200, verbose_name='Opis niezgodności master daty'),
        ),
        migrations.AddField(
            model_name='handlingunititem',
            name='weight_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='Waga [kg]'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='kunnr',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Kod klienta SAP (KUNNR)'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='outbound_created_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Data utworzenia dostawy wychodzącej'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='outbound_delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data dostawy wychodzącej'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='wz_number',
            field=models.CharField(blank=True, max_length=40, verbose_name='Numer WZ'),
        ),
    ]
