# Generated by Django 5.2.16 on 2026-08-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0110_customer_is_vip_customer_kunnr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('manual', 'Ręczne'), ('stock_discrepancy', 'Niezgodność stocku'), ('recurring', 'Cykliczne'), ('zaria_budget', 'Budżet ZARIA'), ('hu_fix', 'Naprawcze (kontrola HU)'), ('hu_stale', 'HU zniknęła z importu'), ('md_exception', 'Niezgodność master daty')], default='manual', max_length=24),
        ),
    ]
