# Generated by Django 5.2.16 on 2026-08-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0111_alter_task_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='priority_rank',
            field=models.PositiveSmallIntegerField(default=0, help_text='Wyższa = wcześniej w kolejce kontroli (tie-break po VIP).', verbose_name='Ranga priorytetu'),
        ),
        migrations.AddField(
            model_name='handlingunit',
            name='called_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Wywołana o'),
        ),
        migrations.AddField(
            model_name='handlingunit',
            name='snooze_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Odłożona do'),
        ),
    ]
