# Generated by Django 5.2.16 on 2026-08-05 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0112_customer_priority_rank_handlingunit_called_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='picking_complete',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Picking zakończony'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='picking_complete_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='picking_eta_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='picking_eta_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picking_eta_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shipment',
            name='picking_eta_note',
            field=models.CharField(blank=True, max_length=200, verbose_name='Status pickingu (ETA)'),
        ),
    ]
