# Generated by Django 5.2.16 on 2026-08-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0113_shipment_picking_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickeractivity',
            name='lot',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Partia / seria'),
        ),
        migrations.AddField(
            model_name='pickeractivity',
            name='material_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='Materiał / indeks'),
        ),
        migrations.AddField(
            model_name='pickeractivity',
            name='qty',
            field=models.FloatField(blank=True, null=True, verbose_name='Ilość'),
        ),
        migrations.AddField(
            model_name='pickeractivity',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='JM'),
        ),
        migrations.AddIndex(
            model_name='pickeractivity',
            index=models.Index(fields=['material_code', 'lot'], name='ui_pickerac_materia_062862_idx'),
        ),
    ]
