# Generated by Django 5.2.16 on 2026-08-06 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0114_pickeractivity_lot_pickeractivity_material_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UkraineOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=120, verbose_name='Klient (Ukraina)')),
                ('order_ref', models.CharField(blank=True, max_length=60, verbose_name='Nr zlecenia')),
                ('index_code', models.CharField(db_index=True, max_length=50, verbose_name='Indeks')),
                ('lot', models.CharField(max_length=32, verbose_name='Partia (LOT)')),
                ('requested_qty', models.FloatField(default=0, verbose_name='Żądana ilość')),
                ('unit', models.CharField(default='szt', max_length=20, verbose_name='Jednostka')),
                ('status', models.CharField(choices=[('open', 'Otwarte'), ('closed', 'Zamknięte')], default='open', max_length=8, verbose_name='Status')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='Uwagi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ukraine_lines', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ui.product')),
            ],
            options={
                'verbose_name': 'Linia wysyłki UKRAINA',
                'verbose_name_plural': 'Linie wysyłki UKRAINA',
                'ordering': ['customer', 'order_ref', 'index_code', 'lot'],
                'indexes': [models.Index(fields=['index_code', 'lot'], name='ui_ukraineo_index_c_b14b93_idx')],
                'constraints': [models.UniqueConstraint(fields=('customer', 'order_ref', 'index_code', 'lot'), name='ukr_line_uniq')],
            },
        ),
    ]
