# Generated by Django 5.2.16 on 2026-08-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0115_ukraineorderline'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='carrier',
            field=models.CharField(blank=True, default='', help_text='np. „GLS”; puste = inny/dowolny', max_length=40, verbose_name='Przewoźnik'),
        ),
        migrations.AddField(
            model_name='customer',
            name='category',
            field=models.CharField(blank=True, choices=[('', 'Standard'), ('vip', 'VIP'), ('delta', 'Delta'), ('beta', 'Beta'), ('export', 'Export')], default='', max_length=20, verbose_name='Kategoria klienta'),
        ),
    ]
