# Generated by Django 5.2.16 on 2026-08-06 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0116_customer_carrier_customer_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hustatusevent',
            name='kind',
            field=models.CharField(choices=[('status', 'zmiana statusu'), ('call', 'wywołanie'), ('release', 'zwolnienie')], db_index=True, default='status', max_length=8),
        ),
        migrations.CreateModel(
            name='EscalationRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_type', models.CharField(blank=True, default='', max_length=40, unique=True, verbose_name='Typ magazynu (pusty = globalna)')),
                ('escalate_after_minutes', models.PositiveSmallIntegerField(default=0, help_text='0 = kierownik zmiany od razu; >0 = dopiero gdy brak reakcji po tym czasie.', verbose_name='Eskaluj do kierownika po [min]')),
                ('area_leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalation_area', to=settings.AUTH_USER_MODEL, verbose_name='Lider obszaru')),
                ('picking_leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalation_picking', to=settings.AUTH_USER_MODEL, verbose_name='Lider pickingu')),
                ('shift_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalation_shift', to=settings.AUTH_USER_MODEL, verbose_name='Kierownik zmiany')),
            ],
            options={
                'verbose_name': 'Ścieżka eskalacji',
                'verbose_name_plural': 'Ścieżki eskalacji',
                'ordering': ['warehouse_type'],
            },
        ),
    ]
