# Generated by Django 5.2.16 on 2026-08-06 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0117_hustatusevent_kind_escalationroute'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagingIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_code', models.CharField(db_index=True, max_length=50, verbose_name='REF / indeks')),
                ('issue_type', models.CharField(choices=[('missing_conversion', 'Brak przelicznika'), ('wrong_conversion', 'Błędny przelicznik'), ('wrong_name', 'Błędna nazwa REF'), ('wrong_date', 'Błędna data (MFG/ważność/seria)'), ('other', 'Inne / uwaga')], max_length=24, verbose_name='Typ zgłoszenia')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Opis')),
                ('current_value', models.CharField(blank=True, max_length=80, verbose_name='Wartość aktualna')),
                ('correct_value', models.CharField(blank=True, max_length=80, verbose_name='Wartość poprawna')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='phv/%Y/%m/', verbose_name='Zdjęcie')),
                ('status', models.CharField(choices=[('open', 'Otwarte'), ('in_review', 'W przeglądzie'), ('resolved', 'Rozwiązane')], db_index=True, default='open', max_length=12)),
                ('resolver_notes', models.CharField(blank=True, max_length=300, verbose_name='Notatka rozwiązania')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ui.product')),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packaging_issues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Zgłoszenie hierarchii opakowań',
                'verbose_name_plural': 'Zgłoszenia hierarchii opakowań',
                'ordering': ['-created_at'],
            },
        ),
    ]
