# Generated by Django 5.2.16 on 2026-08-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0118_packagingissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='hierarchy_levels',
            field=models.CharField(blank=True, default='', help_text='np. „pallet,carton,unit”; puste = pełny szablon', max_length=80, verbose_name='Poziomy hierarchii (CSV)'),
        ),
    ]
