# Generated by Django 5.2.16 on 2026-08-06 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0119_productcategory_hierarchy_levels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlsPackingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartons', models.PositiveSmallIntegerField(verbose_name='Kartony w przygotowaniu')),
                ('parcels', models.PositiveSmallIntegerField(verbose_name='Zrobione paczki')),
                ('volume_m3', models.FloatField(blank=True, null=True, verbose_name='Objętość palety [m³]')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('controller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gls_packing_entries', to=settings.AUTH_USER_MODEL)),
                ('hu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gls_packing', to='ui.handlingunit')),
            ],
            options={
                'verbose_name': 'Rozliczenie pakowania GLS',
                'verbose_name_plural': 'Rozliczenia pakowania GLS',
                'ordering': ['-created_at'],
            },
        ),
    ]
