# Generated by Django 5.2.16 on 2026-08-06 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0120_glspackingentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processmapversion',
            name='process_map',
        ),
        migrations.RemoveField(
            model_name='processmapversion',
            name='author',
        ),
        migrations.DeleteModel(
            name='ProcessMap',
        ),
        migrations.DeleteModel(
            name='ProcessMapVersion',
        ),
    ]
