# Generated by Django 5.2.16 on 2026-08-07 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0121_remove_processmapversion_process_map_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='section',
            field=models.CharField(blank=True, choices=[('GLS', 'GLS'), ('BUS', 'BUS'), ('GEIS', 'GEIS'), ('EXPORT', 'EXPORT')], default='', max_length=20, verbose_name='Sekcja'),
        ),
    ]
