# Generated by Django 5.2.16 on 2026-08-08 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0122_userprofile_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ui_lang',
            field=models.CharField(blank=True, choices=[('pl', 'pl'), ('en', 'en')], default='', max_length=5, verbose_name='Język interfejsu'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ui_theme',
            field=models.CharField(blank=True, choices=[('light', 'light'), ('dark', 'dark')], default='', max_length=5, verbose_name='Motyw interfejsu'),
        ),
    ]
