# Generated by Django 5.2.16 on 2026-08-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0123_userprofile_ui_lang_userprofile_ui_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZariaRolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=60, unique=True, verbose_name='Rola')),
                ('can_compare', models.BooleanField(default=False, verbose_name='Może porównywać modele')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Uprawnienia roli ZARIA',
                'verbose_name_plural': 'Uprawnienia ról ZARIA',
            },
        ),
        migrations.AddField(
            model_name='zariausermodelaccess',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Wygasa (puste = bezterminowo)'),
        ),
        migrations.AddField(
            model_name='zariausermodelaccess',
            name='granted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Nadano'),
        ),
    ]
