# Generated by Django 5.2.16 on 2026-08-08 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0124_zariarolepermission_zariausermodelaccess_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zariaconversation',
            name='compare_mode',
            field=models.BooleanField(default=False, verbose_name='Tryb porównania'),
        ),
        migrations.AddField(
            model_name='zariaconversation',
            name='model_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations_as_b', to='ui.zariamodel', verbose_name='Model B (porównanie)'),
        ),
        migrations.AddField(
            model_name='zariamessage',
            name='compare_group',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='zariamessage',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zariamessage',
            name='variant',
            field=models.CharField(blank=True, choices=[('a', 'A'), ('b', 'B')], default='', max_length=1),
        ),
    ]
