# Generated by Django 5.2.16 on 2026-08-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0125_zariaconversation_compare_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zariaconfig',
            name='retention_days',
            field=models.PositiveIntegerField(default=0, verbose_name='Retencja: usuwaj niezapisane wątki starsze niż N dni (0=nigdy)'),
        ),
        migrations.AddField(
            model_name='zariaconversation',
            name='is_saved',
            field=models.BooleanField(default=False, verbose_name='Zapisany'),
        ),
        migrations.AddField(
            model_name='zariaconversation',
            name='pinned',
            field=models.BooleanField(default=False, verbose_name='Przypięty'),
        ),
        migrations.AddField(
            model_name='zariaconversation',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Tagi (po przecinku)'),
        ),
    ]
