# Generated by Django 5.2.16 on 2026-08-08 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0126_zariaconfig_retention_days_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZariaSystemPromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nazwa')),
                ('body', models.TextField(verbose_name='Treść promptu systemowego')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Kolejność')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Szablon promptu systemowego ZARIA',
                'verbose_name_plural': 'Szablony promptów systemowych ZARIA',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ZariaMailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(blank=True, max_length=300, verbose_name='Do')),
                ('cc', models.CharField(blank=True, max_length=300, verbose_name='DW')),
                ('subject', models.CharField(blank=True, max_length=300, verbose_name='Temat')),
                ('scope', models.CharField(choices=[('last', 'Ostatnia odpowiedź'), ('all', 'Cała rozmowa')], default='last', max_length=8)),
                ('transport', models.CharField(choices=[('mailto', 'mailto'), ('eml', 'plik .eml'), ('graph', 'Microsoft Graph')], default='mailto', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('conversation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mail_logs', to='ui.zariaconversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zaria_mail_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log wysyłki maila ZARIA',
                'verbose_name_plural': 'Logi wysyłek maili ZARIA',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='zariaconversation',
            name='system_prompt_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='ui.zariasystemprompttemplate'),
        ),
    ]
