# Generated by Django 5.2.16 on 2026-08-09 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0128_alter_packagingissue_issue_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouselocationmaster',
            name='blocked_pick',
            field=models.BooleanField(default=False, verbose_name='Blokada wydania'),
        ),
        migrations.AddField(
            model_name='warehouselocationmaster',
            name='blocked_put',
            field=models.BooleanField(default=False, verbose_name='Blokada umieszczania'),
        ),
        migrations.CreateModel(
            name='LocationIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_code', models.CharField(db_index=True, max_length=50, verbose_name='Lokalizacja')),
                ('issue_type', models.CharField(choices=[('damaged_label', 'Uszkodzona etykieta'), ('missing_label', 'Brak etykiety'), ('damaged_beam', 'Uszkodzona belka'), ('missing_hu', 'Brak HU w lokalizacji'), ('other', 'Inne / uwaga')], max_length=24, verbose_name='Typ zgłoszenia')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Opis')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='phv/loc/%Y/%m/', verbose_name='Zdjęcie')),
                ('status', models.CharField(choices=[('open', 'Otwarte'), ('in_review', 'W przeglądzie'), ('resolved', 'Rozwiązane')], db_index=True, default='open', max_length=12)),
                ('resolver_notes', models.CharField(blank=True, max_length=300, verbose_name='Notatka rozwiązania')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_issues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Zgłoszenie lokalizacji',
                'verbose_name_plural': 'Zgłoszenia lokalizacji',
                'ordering': ['-created_at'],
            },
        ),
    ]
