# Generated by Django 5.2.16 on 2026-08-09 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0129_warehouselocationmaster_blocked_pick_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InnerPackArtwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face', models.CharField(choices=[('front', 'Front'), ('back', 'Tył'), ('left', 'Lewy bok'), ('right', 'Prawy bok'), ('top', 'Góra'), ('bottom', 'Dół')], default='front', max_length=10)),
                ('kind', models.CharField(choices=[('print', 'Nadruk ściany'), ('label', 'Etykieta / naklejka')], default='label', max_length=10)),
                ('name', models.CharField(blank=True, max_length=120, verbose_name='Nazwa')),
                ('x_pct', models.FloatField(default=8)),
                ('y_pct', models.FloatField(default=8)),
                ('w_pct', models.FloatField(default=30)),
                ('h_pct', models.FloatField(default=20)),
                ('rotation_deg', models.FloatField(default=0)),
                ('z', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='inner_pack_artwork/', verbose_name='Grafika')),
                ('inner_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='ui.innerpack')),
            ],
            options={
                'verbose_name': 'Grafika OPZ',
                'verbose_name_plural': 'Grafiki OPZ',
                'ordering': ['face', 'z', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductArtwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face', models.CharField(choices=[('front', 'Front'), ('back', 'Tył'), ('left', 'Lewy bok'), ('right', 'Prawy bok'), ('top', 'Góra'), ('bottom', 'Dół')], default='front', max_length=10)),
                ('kind', models.CharField(choices=[('print', 'Nadruk ściany'), ('label', 'Etykieta / naklejka')], default='label', max_length=10)),
                ('name', models.CharField(blank=True, max_length=120, verbose_name='Nazwa')),
                ('x_pct', models.FloatField(default=8)),
                ('y_pct', models.FloatField(default=8)),
                ('w_pct', models.FloatField(default=30)),
                ('h_pct', models.FloatField(default=20)),
                ('rotation_deg', models.FloatField(default=0)),
                ('z', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='product_artwork/', verbose_name='Grafika')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='ui.product')),
            ],
            options={
                'verbose_name': 'Grafika sztuki',
                'verbose_name_plural': 'Grafiki sztuki',
                'ordering': ['face', 'z', 'id'],
                'abstract': False,
            },
        ),
    ]
