# Generated by Django 5.2.16 on 2026-08-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0130_innerpackartwork_productartwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_fill_pct', models.PositiveSmallIntegerField(default=70, help_text='Materiały z wypełnieniem poniżej tej wartości są sygnalizowane jako do optymalizacji (1–100).', verbose_name='Próg dobrego wypełnienia palety [%]')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Konfiguracja optymalizacji',
                'verbose_name_plural': 'Konfiguracja optymalizacji',
            },
        ),
    ]
