# Generated by Django 5.2.16 on 2026-08-09 17:40

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0131_optimizationconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartonAlternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80, verbose_name='Nazwa wariantu')),
                ('length_cm', models.IntegerField(verbose_name='L kartonu [cm]')),
                ('width_cm', models.IntegerField(verbose_name='W kartonu [cm]')),
                ('height_cm', models.IntegerField(verbose_name='H kartonu [cm]')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carton_alternatives', to='ui.product', verbose_name='Materiał')),
            ],
            options={
                'verbose_name': 'Wariant kartonu (optymalizacja)',
                'verbose_name_plural': 'Warianty kartonów (optymalizacja)',
                'ordering': ['product', 'label'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCartonAlternative',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('label', models.CharField(max_length=80, verbose_name='Nazwa wariantu')),
                ('length_cm', models.IntegerField(verbose_name='L kartonu [cm]')),
                ('width_cm', models.IntegerField(verbose_name='W kartonu [cm]')),
                ('height_cm', models.IntegerField(verbose_name='H kartonu [cm]')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ui.product', verbose_name='Materiał')),
            ],
            options={
                'verbose_name': 'historical Wariant kartonu (optymalizacja)',
                'verbose_name_plural': 'historical Warianty kartonów (optymalizacja)',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
