# Generated by Django 5.2.16 on 2026-08-09 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0132_cartonalternative_historicalcartonalternative'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehouselocationtype',
            options={'ordering': ['name'], 'verbose_name': 'Klasa lokalizacji (symulacja)', 'verbose_name_plural': 'Klasy lokalizacji (symulacja)'},
        ),
        migrations.AlterModelOptions(
            name='warehouseracktype',
            options={'ordering': ['code'], 'verbose_name': 'Typ regału (3D)', 'verbose_name_plural': 'Typy regałów (3D)'},
        ),
    ]
