# Generated by Django 5.2.16 on 2026-08-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0133_alter_warehouselocationtype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zariaconversation',
            name='effort',
            field=models.CharField(choices=[('auto', 'Auto'), ('low', 'Niski'), ('medium', 'Średni'), ('high', 'Wysoki')], default='auto', max_length=10, verbose_name='Wysiłek (effort)'),
        ),
    ]
