# Generated by Django 5.2.16 on 2026-08-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0134_zariaconversation_effort'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='must_change_password',
            field=models.BooleanField(default=False, verbose_name='Wymuś zmianę hasła przy logowaniu'),
        ),
    ]
