# Generated by Django 5.2.16 on 2026-08-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0135_userprofile_must_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huqualityissue',
            name='issue_type',
            field=models.CharField(choices=[('wrong_assortment', 'Błędny asortyment / zły indeks'), ('damaged', 'Uszkodzony towar'), ('wrong_batch', 'Błędna seria'), ('ajm_conversion', 'Błąd przelicznika AJM'), ('wrong_expiry', 'Błędna data ważności'), ('bad_placement', 'Nieprawidłowe ułożenie'), ('wrong_label', 'Błąd na etykiecie'), ('missing_document', 'Brak dokumentu / certyfikatu'), ('foreign_item', 'Obcy / nadmiarowy towar')], max_length=24, verbose_name='Typ'),
        ),
    ]
