# Generated by Django 5.2.16 on 2026-08-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0136_alter_huqualityissue_issue_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='handlingunititem',
            name='mfg_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data produkcji'),
        ),
        migrations.AddField(
            model_name='handlingunititem',
            name='vendor_batch',
            field=models.CharField(blank=True, max_length=40, verbose_name='Partia producenta'),
        ),
    ]
