# Generated by Django 5.2.16 on 2026-08-11 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0136_alter_packagingissue_issue_type'),
        ('ui', '0137_handlingunititem_mfg_date_and_more'),
    ]

    operations = [
    ]
