# Generated by Django 5.2.16 on 2026-08-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0138_merge_20260811_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinnerpack',
            name='ean',
            field=models.CharField(blank=True, max_length=30, verbose_name='EAN opak. zbiorczego'),
        ),
        migrations.AddField(
            model_name='historicalinnerpack',
            name='sales_unit_ean',
            field=models.CharField(blank=True, max_length=30, verbose_name='EAN opak. handlowego'),
        ),
        migrations.AddField(
            model_name='innerpack',
            name='ean',
            field=models.CharField(blank=True, max_length=30, verbose_name='EAN opak. zbiorczego'),
        ),
        migrations.AddField(
            model_name='innerpack',
            name='sales_unit_ean',
            field=models.CharField(blank=True, max_length=30, verbose_name='EAN opak. handlowego'),
        ),
    ]
