# Generated by Django 5.2.16 on 2026-08-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0139_innerpack_ean_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='handlingunit',
            name='stock_status',
            field=models.CharField(blank=True, default='', max_length=12, verbose_name='Status zapasu (SAP)'),
        ),
    ]
