# Generated by Django 5.2.16 on 2026-08-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0141_alter_packagingissue_issue_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_code', models.CharField(db_index=True, max_length=40, verbose_name='Miejsce składowania')),
                ('ref_code', models.CharField(db_index=True, max_length=50, verbose_name='REF / produkt')),
                ('warehouse_type', models.CharField(blank=True, default='', max_length=10, verbose_name='Typ magazynu')),
                ('max_qty', models.FloatField(default=0, verbose_name='Ilość maksymalna')),
                ('min_qty', models.FloatField(default=0, verbose_name='Ilość minimalna')),
                ('uom', models.CharField(blank=True, default='', max_length=10, verbose_name='JM')),
                ('changed_at', models.DateField(blank=True, null=True, verbose_name='Data zmiany')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lokalizacja fix',
                'verbose_name_plural': 'Lokalizacje fix',
                'ordering': ['ref_code', 'location_code'],
                'unique_together': {('location_code', 'ref_code')},
            },
        ),
    ]
