# Generated by Django 5.2.16 on 2026-08-13 11:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0142_fixlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='carton',
            name='glb_model',
            field=models.FileField(blank=True, null=True, upload_to='carton_models/', validators=[django.core.validators.FileExtensionValidator(['glb'])], verbose_name='Model 3D (.glb)'),
        ),
        migrations.AddField(
            model_name='historicalcarton',
            name='glb_model',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(['glb'])], verbose_name='Model 3D (.glb)'),
        ),
    ]
