# Generated by Django 5.2.16 on 2026-08-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0143_carton_glb_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartonartwork",
            name="height_px",
            field=models.IntegerField(
                default=0, verbose_name="Wysokość oryginału [px]"
            ),
        ),
        migrations.AddField(
            model_name="cartonartwork",
            name="image_display",
            field=models.ImageField(
                blank=True,
                upload_to="carton_artwork/derived/",
                verbose_name="Grafika (ekran)",
            ),
        ),
        migrations.AddField(
            model_name="cartonartwork",
            name="image_thumb",
            field=models.ImageField(
                blank=True,
                upload_to="carton_artwork/derived/",
                verbose_name="Grafika (miniatura)",
            ),
        ),
        migrations.AddField(
            model_name="cartonartwork",
            name="width_px",
            field=models.IntegerField(
                default=0, verbose_name="Szerokość oryginału [px]"
            ),
        ),
        migrations.AddField(
            model_name="innerpackartwork",
            name="height_px",
            field=models.IntegerField(
                default=0, verbose_name="Wysokość oryginału [px]"
            ),
        ),
        migrations.AddField(
            model_name="innerpackartwork",
            name="image_display",
            field=models.ImageField(
                blank=True,
                upload_to="inner_pack_artwork/derived/",
                verbose_name="Grafika (ekran)",
            ),
        ),
        migrations.AddField(
            model_name="innerpackartwork",
            name="image_thumb",
            field=models.ImageField(
                blank=True,
                upload_to="inner_pack_artwork/derived/",
                verbose_name="Grafika (miniatura)",
            ),
        ),
        migrations.AddField(
            model_name="innerpackartwork",
            name="width_px",
            field=models.IntegerField(
                default=0, verbose_name="Szerokość oryginału [px]"
            ),
        ),
        migrations.AddField(
            model_name="productartwork",
            name="height_px",
            field=models.IntegerField(
                default=0, verbose_name="Wysokość oryginału [px]"
            ),
        ),
        migrations.AddField(
            model_name="productartwork",
            name="image_display",
            field=models.ImageField(
                blank=True,
                upload_to="product_artwork/derived/",
                verbose_name="Grafika (ekran)",
            ),
        ),
        migrations.AddField(
            model_name="productartwork",
            name="image_thumb",
            field=models.ImageField(
                blank=True,
                upload_to="product_artwork/derived/",
                verbose_name="Grafika (miniatura)",
            ),
        ),
        migrations.AddField(
            model_name="productartwork",
            name="width_px",
            field=models.IntegerField(
                default=0, verbose_name="Szerokość oryginału [px]"
            ),
        ),
    ]
