# Generated by Django 5.2.16 on 2026-08-14 06:33

import ui.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0144_cartonartwork_height_px_cartonartwork_image_display_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartonartwork",
            name="image",
            field=models.ImageField(
                upload_to=ui.models.artwork_upload_to, verbose_name="Grafika"
            ),
        ),
        migrations.AlterField(
            model_name="innerpackartwork",
            name="image",
            field=models.ImageField(
                upload_to=ui.models.artwork_upload_to, verbose_name="Grafika"
            ),
        ),
        migrations.AlterField(
            model_name="productartwork",
            name="image",
            field=models.ImageField(
                upload_to=ui.models.artwork_upload_to, verbose_name="Grafika"
            ),
        ),
    ]
