# Generated by Django 5.2.16 on 2026-08-17 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0145_alter_cartonartwork_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_code', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Stary / alternatywny kod')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Uwaga')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='ui.product', verbose_name='Produkt kanoniczny')),
            ],
            options={
                'verbose_name': 'Alias produktu',
                'verbose_name_plural': 'Aliasy produktów',
                'ordering': ['alias_code'],
            },
        ),
    ]
