# Generated by Django 5.2.16 on 2026-08-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0146_productalias'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('process_type', 'Rodzaj procesu')], db_index=True, max_length=32, verbose_name='Kategoria')),
                ('code', models.CharField(max_length=20, verbose_name='Kod')),
                ('label', models.CharField(max_length=200, verbose_name='Opis')),
                ('group', models.CharField(blank=True, max_length=60, verbose_name='Grupa')),
            ],
            options={
                'verbose_name': 'Pojęcie słownika',
                'verbose_name_plural': 'Słownik pojęć',
                'ordering': ['category', 'group', 'code'],
                'constraints': [models.UniqueConstraint(fields=('category', 'code'), name='dict_cat_code_uniq')],
            },
        ),
    ]
