# Generated by Django 5.2.16 on 2026-08-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0149_messagethread_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='handlingunititem',
            name='expiry_ok',
            field=models.BooleanField(default=False, verbose_name='Data ważności potwierdzona'),
        ),
        migrations.AddField(
            model_name='handlingunititem',
            name='vendor_batch_ok',
            field=models.BooleanField(default=False, verbose_name='Partia potwierdzona'),
        ),
    ]
