# Generated by Django 5.2.16 on 2026-08-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0150_handlingunititem_expiry_ok_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='ack_group',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='notification',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='requires_ack',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
