# Generated by Django 5.2.16 on 2026-08-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0151_notification_ack_group_notification_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hucontrolattempt',
            name='device_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='hucontrolattempt',
            name='input_source',
            field=models.CharField(blank=True, default='', max_length=12, verbose_name='Źródło inputu'),
        ),
    ]
