# Generated by Django 5.2.16 on 2026-08-19 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0152_hucontrolattempt_device_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HULabelPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='pickHU')),
                ('label_id', models.CharField(max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='label_pairs', to='ui.huprintrun')),
            ],
            options={
                'verbose_name': 'Para etykiety HU',
                'verbose_name_plural': 'Pary etykiet HU',
            },
        ),
    ]
