# Generated by Django 5.2.16 on 2026-08-20 07:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0153_hulabelpair'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='glb_model',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(['glb'])], verbose_name='Model 3D (.glb)'),
        ),
        migrations.AddField(
            model_name='product',
            name='glb_model',
            field=models.FileField(blank=True, null=True, upload_to='product_models/', validators=[django.core.validators.FileExtensionValidator(['glb'])], verbose_name='Model 3D (.glb)'),
        ),
    ]
