# Generated by Django 5.2.16 on 2026-08-20 09:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0154_historicalproduct_glb_model_product_glb_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='ju_glb_model',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(['glb'])], verbose_name='Model 3D sztuki JU (.glb)'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='ju_image',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='Zdjęcie sztuki JU (PNG/JPG)'),
        ),
        migrations.AddField(
            model_name='product',
            name='ju_glb_model',
            field=models.FileField(blank=True, null=True, upload_to='product_models/', validators=[django.core.validators.FileExtensionValidator(['glb'])], verbose_name='Model 3D sztuki JU (.glb)'),
        ),
        migrations.AddField(
            model_name='product',
            name='ju_image',
            field=models.FileField(blank=True, null=True, upload_to='product_art/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='Zdjęcie sztuki JU (PNG/JPG)'),
        ),
    ]
