# Generated by Django 5.2.16 on 2026-08-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0155_historicalproduct_ju_glb_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagingissue',
            name='issue_type',
            field=models.CharField(choices=[('missing_conversion', 'Brak przelicznika'), ('wrong_conversion', 'Błędny przelicznik'), ('wrong_name', 'Błędna nazwa REF'), ('wrong_date', 'Błędna data (MFG/ważność/seria)'), ('carton_too_heavy', 'Karton za ciężki'), ('change_location', 'Zmień lokalizację'), ('carton_underfilled', 'Karton niewypełniony (do optymalizacji)'), ('carton_fit_pallet', 'Dopasować karton do wymiarów palety'), ('missing_process', 'Brak procesu magazynowego'), ('missing_render', 'Brak renderu 3D — zdjęcie jednostki'), ('other', 'Inne / uwaga')], max_length=24, verbose_name='Typ zgłoszenia'),
        ),
    ]
