# Generated by Django 5.2.16 on 2026-08-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0156_alter_packagingissue_issue_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_device',
            field=models.CharField(blank=True, choices=[('zebra', 'Zebra'), ('mobile', 'Telefon'), ('desktop', 'Komputer')], default='', max_length=12, verbose_name='Ostatnie urządzenie'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Ostatnia aktywność'),
        ),
    ]
