# Generated by Django 5.2.16 on 2026-08-20 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0157_userprofile_last_device_userprofile_last_seen_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPackagingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units_per_pack', models.PositiveIntegerField(verbose_name='Szt / opakowanie')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Uwagi')),
                ('alert_email', models.EmailField(blank=True, max_length=254, verbose_name='Alert e-mail')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywna')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packaging_rules', to='ui.customer', verbose_name='Klient')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_packaging_rules', to='ui.product', verbose_name='Indeks')),
            ],
            options={
                'verbose_name': 'Reguła pakowania klienta',
                'verbose_name_plural': 'Reguły pakowania klienta',
                'unique_together': {('customer', 'product')},
            },
        ),
    ]
