# Generated by Django 5.2.16 on 2026-08-20 19:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0158_customerpackagingrule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagingRedesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('op', 'Opakowanie (OP)'), ('karton', 'Karton'), ('oba', 'OP + karton')], max_length=8, verbose_name='Zakres')),
                ('a_snapshot', models.JSONField(verbose_name='Wersja A (snapshot)')),
                ('a_render', models.FileField(blank=True, null=True, upload_to='redesigns/', validators=[django.core.validators.FileExtensionValidator(['glb', 'png', 'jpg', 'jpeg'])], verbose_name='Render wersji A')),
                ('b_op_l', models.FloatField(blank=True, null=True, verbose_name='B: L opakowania [cm]')),
                ('b_op_w', models.FloatField(blank=True, null=True, verbose_name='B: W opakowania [cm]')),
                ('b_op_h', models.FloatField(blank=True, null=True, verbose_name='B: H opakowania [cm]')),
                ('b_carton_l', models.FloatField(blank=True, null=True, verbose_name='B: L kartonu [cm]')),
                ('b_carton_w', models.FloatField(blank=True, null=True, verbose_name='B: W kartonu [cm]')),
                ('b_carton_h', models.FloatField(blank=True, null=True, verbose_name='B: H kartonu [cm]')),
                ('b_pcs_per_carton', models.PositiveIntegerField(blank=True, null=True, verbose_name='B: szt/karton')),
                ('b_units_per_pack', models.PositiveIntegerField(blank=True, null=True, verbose_name='B: szt/OP')),
                ('annual_volume_pcs', models.PositiveIntegerField(blank=True, null=True, verbose_name='Wolumen roczny [szt]')),
                ('status', models.CharField(choices=[('draft', 'Szkic'), ('accepted', 'Zaakceptowany'), ('rejected', 'Odrzucony')], db_index=True, default='draft', max_length=10, verbose_name='Status')),
                ('notes', models.TextField(blank=True, max_length=1000, verbose_name='Notatki')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redesigns', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redesigns', to='ui.product', verbose_name='Indeks')),
            ],
            options={
                'verbose_name': 'Projekt A/B opakowania',
                'verbose_name_plural': 'Projekty A/B opakowań',
                'ordering': ['-created_at'],
            },
        ),
    ]
