# Generated by Django 5.2.16 on 2026-08-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0159_packagingredesign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_device',
            field=models.CharField(blank=True, choices=[('zebra', 'Zebra'), ('mobile', 'Telefon'), ('tablet', 'Tablet'), ('desktop', 'Komputer')], default='', max_length=12, verbose_name='Ostatnie urządzenie'),
        ),
    ]
