# Generated by Django 5.2.16 on 2026-08-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0160_alter_userprofile_last_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimizationconfig',
            name='suggest_vol_down_pct',
            field=models.PositiveSmallIntegerField(default=20, help_text='O ile mniejszy karton wolno zaproponować niż obecny (0–90).', verbose_name='Auto-sugestia: dopuszczalne zmniejszenie objętości [%]'),
        ),
        migrations.AddField(
            model_name='optimizationconfig',
            name='suggest_vol_up_pct',
            field=models.PositiveSmallIntegerField(default=20, help_text='O ile większy karton wolno zaproponować niż obecny (0–100).', verbose_name='Auto-sugestia: dopuszczalne zwiększenie objętości [%]'),
        ),
    ]
