# Generated by Django 5.2.16 on 2026-08-22 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0161_optimizationconfig_suggest_bands'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartonPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(verbose_name='Wersja instrukcji (wynikowa)')),
                ('dims', models.CharField(max_length=40, verbose_name='Wymiary kartonu')),
                ('source_label', models.CharField(blank=True, max_length=80, verbose_name='Źródło (wariant)')),
                ('fill_before', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Wypełnienie przed [%]')),
                ('fill_after', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Wypełnienie po [%]')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions', to='ui.packagingissue', verbose_name='Ze zgłoszenia')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carton_promotions', to='ui.product', verbose_name='Materiał')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carton_promotions', to=settings.AUTH_USER_MODEL, verbose_name='Wykonał')),
            ],
            options={
                'verbose_name': 'Promocja kartonu (historia)',
                'verbose_name_plural': 'Promocje kartonów (historia)',
                'ordering': ['-created_at'],
            },
        ),
    ]
