# Generated by Django 5.2.16 on 2026-08-22 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0162_cartonpromotion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='packagingissue',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Przyjęto'),
        ),
        migrations.AddField(
            model_name='packagingissue',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_packaging_issues', to=settings.AUTH_USER_MODEL, verbose_name='Przyjęte przez'),
        ),
    ]
