# Generated by Django 5.2.16 on 2026-08-23 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0163_packagingissue_assigned_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HULabelPair',
        ),
    ]
