# Generated by Django 5.2.16 on 2026-08-23 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0164_delete_hulabelpair'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HUControlPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='hu_control/%Y/%m/', verbose_name='Zdjęcie')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('hu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_photos', to='ui.handlingunit')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kontroler')),
            ],
            options={
                'verbose_name': 'Zdjęcie kontroli HU',
                'verbose_name_plural': 'Zdjęcia kontroli HU',
                'ordering': ['-created_at'],
            },
        ),
    ]
