# Generated by Django 5.2.16 on 2026-08-23 14:10

from django.conf import settings
from django.db import migrations, models


def dedup_redesigns(apps, schema_editor):
    """Jeden indeks = jeden projekt. Przed constraintem scal duplikaty: dla każdego
    produktu zostaw JEDEN rekord — zaakceptowany, jeśli istnieje; inaczej najnowszy
    (największe id). Resztę usuń. Idempotentne (drugie przejście = 0 duplikatów)."""
    Redesign = apps.get_model("ui", "PackagingRedesign")
    from collections import defaultdict
    by_product = defaultdict(list)
    for rd in Redesign.objects.all().order_by("-id"):
        by_product[rd.product_id].append(rd)
    for rows in by_product.values():
        if len(rows) < 2:
            continue
        accepted = [r for r in rows if r.status == "accepted"]
        keep = accepted[0] if accepted else rows[0]   # rows już malejąco po id → [0] = najnowszy
        for r in rows:
            if r.pk != keep.pk:
                r.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0165_hucontrolphoto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(dedup_redesigns, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='packagingredesign',
            constraint=models.UniqueConstraint(fields=('product',), name='uniq_redesign_per_product'),
        ),
    ]
