# Generated by Django 5.2.16 on 2026-08-23 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0166_redesign_one_per_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseHallFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('dock', 'Dok przeładunkowy'), ('gate', 'Brama'), ('corridor', 'Korytarz / ciąg komunikacyjny'), ('block_zone', 'Strefa blokowa / nietypowa'), ('returns', 'Strefa zwrotów'), ('leader', 'Stanowisko lidera'), ('station', 'Stanowisko / punkt kontroli'), ('other', 'Inny obszar')], default='other', max_length=20, verbose_name='Typ elementu')),
                ('label', models.CharField(blank=True, max_length=100, verbose_name='Etykieta')),
                ('zone_code', models.CharField(blank=True, help_text='Dla stref blokowych/zwrotów — łapie kody po prefiksie', max_length=20, verbose_name='Prefiks kodów lokalizacji')),
                ('x_m', models.FloatField(default=0, verbose_name='Pozycja X [m]')),
                ('y_m', models.FloatField(default=0, verbose_name='Pozycja Y [m]')),
                ('width_m', models.FloatField(default=2, verbose_name='Szerokość [m]')),
                ('depth_m', models.FloatField(default=2, verbose_name='Głębokość [m]')),
                ('angle_deg', models.FloatField(default=0, verbose_name='Kąt obrotu [°]')),
                ('color_hex', models.CharField(blank=True, max_length=7, verbose_name='Kolor')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Uwagi')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='ui.warehousemodel')),
            ],
            options={
                'verbose_name': 'Element hali',
                'verbose_name_plural': 'Elementy hali',
                'ordering': ['kind', 'label'],
            },
        ),
    ]
