# Generated by Django 5.2.16 on 2026-08-23 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0167_warehousehallfeature'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseAisleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aisle', models.CharField(max_length=30, verbose_name='Aleja')),
                ('width_m', models.FloatField(default=2.0, verbose_name='Szerokość korytarza [m]')),
                ('angle_deg', models.FloatField(default=0, verbose_name='Kąt obrotu [°]')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Uwagi')),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aisles', to='ui.warehouselayout')),
            ],
            options={
                'verbose_name': 'Konfiguracja alei',
                'verbose_name_plural': 'Konfiguracje alej',
                'ordering': ['aisle'],
                'unique_together': {('layout', 'aisle')},
            },
        ),
    ]
