# Generated by Django 5.2.16 on 2026-08-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0168_warehouseaisleconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseracktype',
            name='level_weights',
            field=models.JSONField(default=dict, help_text='np. {"1":1000,"2":300} — max waga na poziom (etykiety kg w widoku 3D).', verbose_name='Nośność poziomów [kg]'),
        ),
    ]
