# Generated by Django 5.2.16 on 2026-08-23 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0169_warehouseracktype_level_weights'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousehallfeature',
            name='layout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='ui.warehouselayout'),
        ),
        migrations.AlterField(
            model_name='warehousehallfeature',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='ui.warehousemodel'),
        ),
    ]
