# Generated by Django 5.2.16 on 2026-08-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0170_warehousehallfeature_layout_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='warehousehallfeature',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('layout__isnull', True), ('model__isnull', False)), models.Q(('layout__isnull', False), ('model__isnull', True)), _connector='OR'), name='hallfeature_one_owner'),
        ),
    ]
