# Generated by Django 5.2.16 on 2026-08-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0171_warehousehallfeature_hallfeature_one_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartonalternative',
            name='pack_h_cm',
            field=models.IntegerField(blank=True, null=True, verbose_name='H OPZ [cm]'),
        ),
        migrations.AddField(
            model_name='cartonalternative',
            name='pack_l_cm',
            field=models.IntegerField(blank=True, null=True, verbose_name='L OPZ [cm]'),
        ),
        migrations.AddField(
            model_name='cartonalternative',
            name='pack_w_cm',
            field=models.IntegerField(blank=True, null=True, verbose_name='W OPZ [cm]'),
        ),
        migrations.AddField(
            model_name='cartonalternative',
            name='slot',
            field=models.CharField(blank=True, choices=[('', '—'), ('B', 'B'), ('C', 'C')], default='', max_length=1, verbose_name='Slot porównania'),
        ),
        migrations.AddField(
            model_name='cartonalternative',
            name='unit_h_cm',
            field=models.IntegerField(blank=True, null=True, verbose_name='H sztuki [cm]'),
        ),
        migrations.AddField(
            model_name='cartonalternative',
            name='unit_l_cm',
            field=models.IntegerField(blank=True, null=True, verbose_name='L sztuki [cm]'),
        ),
        migrations.AddField(
            model_name='cartonalternative',
            name='unit_w_cm',
            field=models.IntegerField(blank=True, null=True, verbose_name='W sztuki [cm]'),
        ),
        migrations.AddField(
            model_name='historicalcartonalternative',
            name='pack_h_cm',
            field=models.IntegerField(blank=True, null=True, verbose_name='H OPZ [cm]'),
        ),
        migrations.AddField(
            model_name='historicalcartonalternative',
            name='pack_l_cm',
            field=models.IntegerField(blank=True, null=True, verbose_name='L OPZ [cm]'),
        ),
        migrations.AddField(
            model_name='historicalcartonalternative',
            name='pack_w_cm',
            field=models.IntegerField(blank=True, null=True, verbose_name='W OPZ [cm]'),
        ),
        migrations.AddField(
            model_name='historicalcartonalternative',
            name='slot',
            field=models.CharField(blank=True, choices=[('', '—'), ('B', 'B'), ('C', 'C')], default='', max_length=1, verbose_name='Slot porównania'),
        ),
        migrations.AddField(
            model_name='historicalcartonalternative',
            name='unit_h_cm',
            field=models.IntegerField(blank=True, null=True, verbose_name='H sztuki [cm]'),
        ),
        migrations.AddField(
            model_name='historicalcartonalternative',
            name='unit_l_cm',
            field=models.IntegerField(blank=True, null=True, verbose_name='L sztuki [cm]'),
        ),
        migrations.AddField(
            model_name='historicalcartonalternative',
            name='unit_w_cm',
            field=models.IntegerField(blank=True, null=True, verbose_name='W sztuki [cm]'),
        ),
    ]
