# Generated by Django 5.2.16 on 2026-08-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0172_cartonalternative_pack_h_cm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseracktype',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Opis (znaczenie kodu)'),
        ),
        migrations.AddField(
            model_name='warehouseracktype',
            name='kind',
            field=models.CharField(choices=[('rack', 'Regał'), ('zone', 'Strefa')], default='rack', max_length=8, verbose_name='Rodzaj'),
        ),
    ]
