# Generated by Django 5.2.16 on 2026-08-25 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0174_seed_rack_type_dictionary'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimizationconfig',
            name='pallets_per_truck',
            field=models.PositiveSmallIntegerField(default=33, help_text='Pojemność auta do KPI aut/rok (1–66). Standard FTL: 33 palety EU.', verbose_name='Palet na auto [szt]'),
        ),
    ]
