# Generated by Django 5.2.16 on 2026-08-25 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0175_optimizationconfig_pallets_per_truck'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportKpiSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict, verbose_name='Dane KPI (kpi + charts)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ostatnie przeliczenie')),
            ],
            options={
                'verbose_name': 'Snapshot KPI transportu',
                'verbose_name_plural': 'Snapshot KPI transportu',
            },
        ),
    ]
