# Generated by Django 5.2.16 on 2026-08-25 04:54

from django.conf import settings
from django.db import migrations, models


def _close_duplicate_open_tasks(apps, schema_editor):
    Task = apps.get_model("ui", "Task")
    from django.db.models import Count
    dupes = (Task.objects.exclude(status="done").exclude(dedup_key="")
             .values("dedup_key").annotate(n=Count("id")).filter(n__gt=1))
    for row in dupes:
        ids = list(Task.objects.filter(dedup_key=row["dedup_key"]).exclude(status="done")
                   .order_by("-created_at").values_list("id", flat=True))
        Task.objects.filter(id__in=ids[1:]).update(status="done")


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0176_transportkpisnapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Zanim wejdzie constraint: domknij historyczne duplikaty (zostaje najnowsze
        # otwarte zadanie per dedup_key, starsze → done), inaczej AddConstraint padnie.
        migrations.RunPython(_close_duplicate_open_tasks, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('status', 'done'), _negated=True), models.Q(('dedup_key', ''), _negated=True)), fields=('dedup_key',), name='uniq_open_task_per_dedup_key'),
        ),
    ]
