# Generated by Django 5.2.16 on 2026-08-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0181_productviewhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carton',
            name='ean',
            field=models.CharField(blank=True, db_index=True, max_length=30, verbose_name='EAN opakowania'),
        ),
        migrations.AlterField(
            model_name='historicalcarton',
            name='ean',
            field=models.CharField(blank=True, db_index=True, max_length=30, verbose_name='EAN opakowania'),
        ),
        migrations.AlterField(
            model_name='historicalinnerpack',
            name='ean',
            field=models.CharField(blank=True, db_index=True, max_length=30, verbose_name='EAN opak. zbiorczego'),
        ),
        migrations.AlterField(
            model_name='historicalinnerpack',
            name='sales_unit_ean',
            field=models.CharField(blank=True, db_index=True, max_length=30, verbose_name='EAN opak. handlowego'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='ean',
            field=models.CharField(blank=True, db_index=True, max_length=30, verbose_name='EAN / barcode'),
        ),
        migrations.AlterField(
            model_name='innerpack',
            name='ean',
            field=models.CharField(blank=True, db_index=True, max_length=30, verbose_name='EAN opak. zbiorczego'),
        ),
        migrations.AlterField(
            model_name='innerpack',
            name='sales_unit_ean',
            field=models.CharField(blank=True, db_index=True, max_length=30, verbose_name='EAN opak. handlowego'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ean',
            field=models.CharField(blank=True, db_index=True, max_length=30, verbose_name='EAN / barcode'),
        ),
    ]
