# Generated by Django 5.2.16 on 2026-08-25 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0183_alter_packagingissue_issue_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpalletizationinstruction',
            name='variant',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], db_index=True, default='A', max_length=1, verbose_name='Wariant paletyzacji'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='active_variant',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], default='A', max_length=1, verbose_name='Obowiązujący wariant paletyzacji'),
        ),
        migrations.AddField(
            model_name='palletizationinstruction',
            name='variant',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], db_index=True, default='A', max_length=1, verbose_name='Wariant paletyzacji'),
        ),
        migrations.AddField(
            model_name='product',
            name='active_variant',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], default='A', max_length=1, verbose_name='Obowiązujący wariant paletyzacji'),
        ),
        migrations.AlterField(
            model_name='packagingissue',
            name='issue_type',
            field=models.CharField(choices=[('missing_conversion', 'Brak przelicznika'), ('wrong_conversion', 'Błędny przelicznik'), ('wrong_name', 'Błędna nazwa REF'), ('wrong_date', 'Błędna data (MFG/ważność/seria)'), ('carton_too_heavy', 'Karton za ciężki'), ('change_location', 'Zmień lokalizację'), ('carton_underfilled', 'Karton niewypełniony (do optymalizacji)'), ('carton_fit_pallet', 'Dopasować karton do wymiarów palety'), ('missing_process', 'Brak procesu magazynowego'), ('missing_render', 'Brak renderu 3D — zdjęcie jednostki'), ('change_palletization', 'Zmień sposób paletyzacji'), ('verify_volume', 'Zweryfikuj objętość produktu'), ('packspec_mismatch', 'Rozbieżność packspec / MARM'), ('other', 'Inne / uwaga')], max_length=24, verbose_name='Typ zgłoszenia'),
        ),
        migrations.CreateModel(
            name='PackSpecBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nazwa partii')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Wgrano')),
                ('row_count', models.PositiveIntegerField(default=0, verbose_name='Liczba wierszy')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywna')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partia packspec',
                'verbose_name_plural': 'Partie packspec',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PackSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_code', models.CharField(db_index=True, max_length=50, verbose_name='REF / indeks')),
                ('pcs_per_carton', models.PositiveIntegerField(blank=True, null=True, verbose_name='Szt / karton (packspec)')),
                ('cartons_per_pallet', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kartony / paleta (packspec)')),
                ('pcs_per_pallet', models.PositiveIntegerField(blank=True, null=True, verbose_name='Szt / paleta (packspec)')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Uwagi')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packspecs', to='ui.product')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='ui.packspecbatch')),
            ],
            options={
                'verbose_name': 'Packspec',
                'verbose_name_plural': 'Packspec',
                'ordering': ['ref_code'],
            },
        ),
    ]
