# Generated by Django 5.2.16 on 2026-08-25 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0184_historicalpalletizationinstruction_variant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('products', 'Produkty (pełny szablon)'), ('marm', 'SAP MARM'), ('cartons', 'Kartony'), ('inner_packs', 'Opakowania zbiorcze'), ('categories', 'Kategorie'), ('ref_materials', 'Materiały referencyjne'), ('fix_locations', 'Fixy (stałe lokalizacje)'), ('customers', 'Klienci'), ('users', 'Użytkownicy'), ('locations_master', 'Lokalizacje — master'), ('warehouse_snapshot', 'Snapshot zajętości (SAP WMS)'), ('warehouse_layout', 'Layout magazynu'), ('picker_activity', 'Aktywność pickerów (heatmapa)'), ('hu_stock_file', 'Wsad HU (plik)'), ('hu_stock_powerbi', 'Stock z Power BI'), ('packspec', 'Packspec przyjęć')], db_index=True, max_length=32, verbose_name='Źródło danych')),
                ('label', models.CharField(blank=True, max_length=200, verbose_name='Etykieta (np. plik)')),
                ('status', models.CharField(choices=[('ok', 'OK'), ('error', 'Błąd'), ('running', 'W toku')], default='ok', max_length=8)),
                ('row_count', models.PositiveIntegerField(default=0, verbose_name='Liczba rekordów')),
                ('error_message', models.CharField(blank=True, max_length=400, verbose_name='Ostatni błąd')),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Uruchomił')),
            ],
            options={
                'verbose_name': 'Przebieg importu',
                'verbose_name_plural': 'Przebiegi importów',
                'ordering': ['-started_at'],
            },
        ),
    ]
