# Generated by Django 5.2.16 on 2026-08-25 16:01

from django.db import migrations


# W2: zdjęcie modeli magazynu ze stanu aplikacji ui — tabele ui_* zostają
# (przejęte przez wh3d.0001_initial). Zero SQL.
class Migration(migrations.Migration):

    dependencies = [
        ("wh3d", "0001_initial"),
        ('ui', '0185_importrun'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=[
        migrations.RemoveField(
            model_name='pickeractivity',
            name='batch',
        ),
        migrations.AlterUniqueTogether(
            name='warehouseaisleconfig',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='warehouseaisleconfig',
            name='layout',
        ),
        migrations.RemoveField(
            model_name='warehousehallfeature',
            name='layout',
        ),
        migrations.RemoveField(
            model_name='warehousehallfeature',
            name='model',
        ),
        migrations.RemoveField(
            model_name='warehouselayoutcell',
            name='layout',
        ),
        migrations.AlterUniqueTogether(
            name='warehouselayoutcell',
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name='warehouselocationmaster',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='warehouselocationmaster',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='warehousemodelrack',
            name='model',
        ),
        migrations.AlterUniqueTogether(
            name='warehousemodelrack',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='WarehouseRackType',
        ),
        migrations.RemoveField(
            model_name='warehousesnapshotrow',
            name='snapshot',
        ),
        migrations.DeleteModel(
            name='PickerActivity',
        ),
        migrations.DeleteModel(
            name='PickerActivityBatch',
        ),
        migrations.DeleteModel(
            name='WarehouseAisleConfig',
        ),
        migrations.DeleteModel(
            name='WarehouseHallFeature',
        ),
        migrations.DeleteModel(
            name='WarehouseLayout',
        ),
        migrations.DeleteModel(
            name='WarehouseLayoutCell',
        ),
        migrations.DeleteModel(
            name='WarehouseLocationMaster',
        ),
        migrations.DeleteModel(
            name='WarehouseLocationMasterBatch',
        ),
        migrations.DeleteModel(
            name='WarehouseModel',
        ),
        migrations.DeleteModel(
            name='WarehouseModelRack',
        ),
        migrations.DeleteModel(
            name='WarehouseSnapshot',
        ),
        migrations.DeleteModel(
            name='WarehouseSnapshotRow',
        )
        ]),
    ]
