# Generated by Django 5.2.16 on 2026-08-25 18:46

import django.db.models.deletion
from django.db import migrations, models


# W2 wydzielenia Kontroli HU: zdjęcie modeli ze stanu ui (tabele przejęte przez huctl)
# — wyłącznie zmiana stanu, zero SQL (SeparateDatabaseAndState).
class Migration(migrations.Migration):

    dependencies = [
        ('huctl', '0001_initial'),
        ('ui', '0186_remove_pickeractivity_batch_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=[
        migrations.DeleteModel(
            name='ControlledWarehouseType',
        ),
        migrations.RemoveField(
            model_name='escalationroute',
            name='area_leader',
        ),
        migrations.RemoveField(
            model_name='escalationroute',
            name='picking_leader',
        ),
        migrations.RemoveField(
            model_name='escalationroute',
            name='shift_manager',
        ),
        migrations.RemoveField(
            model_name='glspackingentry',
            name='controller',
        ),
        migrations.RemoveField(
            model_name='glspackingentry',
            name='hu',
        ),
        migrations.AlterUniqueTogether(
            name='handlingunit',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='handlingunit',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='handlingunit',
            name='client_reqs_confirmed_by',
        ),
        migrations.RemoveField(
            model_name='handlingunit',
            name='controlled_by',
        ),
        migrations.RemoveField(
            model_name='handlingunit',
            name='shipment',
        ),
        migrations.RemoveField(
            model_name='handlingunit',
            name='short_dated_ack_by',
        ),
        migrations.RemoveField(
            model_name='hucontrolattempt',
            name='hu',
        ),
        migrations.RemoveField(
            model_name='huqualityissue',
            name='hu',
        ),
        migrations.RemoveField(
            model_name='handlingunititem',
            name='hu',
        ),
        migrations.RemoveField(
            model_name='hustatusevent',
            name='hu',
        ),
        migrations.AlterField(
            model_name='task',
            name='related_hu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='huctl.handlingunit', verbose_name='Powiązany HU'),
        ),
        migrations.RemoveField(
            model_name='hucontrolphoto',
            name='hu',
        ),
        migrations.RemoveField(
            model_name='handlingunititem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='hucontrolattempt',
            name='item',
        ),
        migrations.RemoveField(
            model_name='huqualityissue',
            name='item',
        ),
        migrations.RemoveField(
            model_name='hucontrolattempt',
            name='controller',
        ),
        migrations.RemoveField(
            model_name='hucontrolphoto',
            name='user',
        ),
        migrations.RemoveField(
            model_name='huprintrun',
            name='project',
        ),
        migrations.RemoveField(
            model_name='huprintrun',
            name='user',
        ),
        migrations.RemoveField(
            model_name='huqualityissue',
            name='closed_by',
        ),
        migrations.RemoveField(
            model_name='huqualityissue',
            name='raised_by',
        ),
        migrations.RemoveField(
            model_name='hustatusevent',
            name='by_user',
        ),
        migrations.DeleteModel(
            name='ControllerZone',
        ),
        migrations.DeleteModel(
            name='EscalationRoute',
        ),
        migrations.DeleteModel(
            name='GlsPackingEntry',
        ),
        migrations.DeleteModel(
            name='HandlingUnit',
        ),
        migrations.DeleteModel(
            name='HandlingUnitItem',
        ),
        migrations.DeleteModel(
            name='HUControlAttempt',
        ),
        migrations.DeleteModel(
            name='HUControlPhoto',
        ),
        migrations.DeleteModel(
            name='HUPrintProject',
        ),
        migrations.DeleteModel(
            name='HUPrintRun',
        ),
        migrations.DeleteModel(
            name='HUQualityIssue',
        ),
        migrations.DeleteModel(
            name='HUStatusEvent',
        ),
        ]),
    ]
