# Generated by Django 5.2.16 on 2026-08-25 20:07

from django.db import migrations


# W2 wydzielenia Transportu: zdjęcie modeli ze stanu ui (tabele przejęte przez transport)
# — wyłącznie zmiana stanu, zero SQL (SeparateDatabaseAndState).
class Migration(migrations.Migration):

    dependencies = [
        ('huctl', '0002_alter_handlingunit_shipment'),
        ('ui', '0187_delete_controlledwarehousetype_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=[
        migrations.RemoveField(
            model_name='carrierzone',
            name='carrier',
        ),
        migrations.RemoveField(
            model_name='carrierrate',
            name='zone',
        ),
        migrations.RemoveField(
            model_name='driverassignment',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='driverassignment',
            name='shipment',
        ),
        migrations.RemoveField(
            model_name='shipmentquoteoffer',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='picking_eta_by',
        ),
        migrations.RemoveField(
            model_name='shipmentquoteoffer',
            name='shipment',
        ),
        migrations.RemoveField(
            model_name='warehousereadiness',
            name='shipment',
        ),
        migrations.RemoveField(
            model_name='shipmentline',
            name='shipment',
        ),
        migrations.AlterUniqueTogether(
            name='shipmentline',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='shipmentline',
            name='product',
        ),
        migrations.AlterUniqueTogether(
            name='shipmentquoteoffer',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='TransportKpiSnapshot',
        ),
        migrations.AlterUniqueTogether(
            name='warehousereadiness',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='Carrier',
        ),
        migrations.DeleteModel(
            name='CarrierRate',
        ),
        migrations.DeleteModel(
            name='CarrierZone',
        ),
        migrations.DeleteModel(
            name='DriverAssignment',
        ),
        migrations.DeleteModel(
            name='QuoteRecipient',
        ),
        migrations.DeleteModel(
            name='ShipmentQuoteOffer',
        ),
        migrations.DeleteModel(
            name='WarehouseReadiness',
        ),
        migrations.DeleteModel(
            name='Shipment',
        ),
        migrations.DeleteModel(
            name='ShipmentLine',
        ),
        ]),
    ]
