# Generated by Django 5.2.16 on 2026-09-01 03:59

from django.db import migrations, models


def _backfill(apps, schema_editor):
    """Kto miał sekcję (motyw), zaczyna z nią jako jedyną dozwoloną strefą kontroli."""
    UserProfile = apps.get_model("ui", "UserProfile")
    for prof in UserProfile.objects.exclude(section="").filter(allowed_sections=""):
        prof.allowed_sections = prof.section
        prof.save(update_fields=["allowed_sections"])


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0188_remove_carrierzone_carrier_remove_carrierrate_zone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allowed_sections',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Dozwolone strefy kontroli'),
        ),
        migrations.RunPython(_backfill, migrations.RunPython.noop),
    ]
