# Generated by Django 5.2.16 on 2026-09-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0189_userprofile_allowed_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpalletizationinstruction',
            name='custom_layout_stale',
            field=models.BooleanField(default=False, verbose_name='Ręczny układ może być nieaktualny'),
        ),
        migrations.AddField(
            model_name='palletizationinstruction',
            name='custom_layout_stale',
            field=models.BooleanField(default=False, verbose_name='Ręczny układ może być nieaktualny'),
        ),
    ]
