# Generated by Django 5.2.16 on 2026-09-11 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0190_historicalpalletizationinstruction_custom_layout_stale_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='importrun',
            name='kind',
            field=models.CharField(choices=[('products', 'Produkty (pełny szablon)'), ('marm', 'SAP MARM'), ('cartons', 'Kartony'), ('inner_packs', 'Opakowania zbiorcze'), ('categories', 'Kategorie'), ('ref_materials', 'Materiały referencyjne'), ('fix_locations', 'Fixy (stałe lokalizacje)'), ('customers', 'Klienci'), ('users', 'Użytkownicy'), ('locations_master', 'Lokalizacje — master'), ('warehouse_snapshot', 'Snapshot zajętości (SAP WMS)'), ('warehouse_layout', 'Layout magazynu'), ('picker_activity', 'Aktywność pickerów (heatmapa)'), ('hu_stock_file', 'Wsad HU (plik)'), ('hu_stock_powerbi', 'Stock z Power BI'), ('packspec', 'Packspec przyjęć'), ('producer_dims', 'Wymiary producenta')], db_index=True, max_length=32, verbose_name='Źródło danych'),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('manual', 'Ręczne'), ('stock_discrepancy', 'Niezgodność stocku'), ('recurring', 'Cykliczne'), ('zaria_budget', 'Budżet ZARIA'), ('hu_fix', 'Naprawcze (kontrola HU)'), ('hu_stale', 'HU zniknęła z importu'), ('md_exception', 'Niezgodność master daty'), ('carton_dim_mismatch', 'Rozjazd wymiarów kartonu')], default='manual', max_length=24),
        ),
        migrations.CreateModel(
            name='ProducerCartonBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(db_index=True, max_length=120, verbose_name='Dostawca')),
                ('source_filename', models.CharField(blank=True, max_length=255, verbose_name='Plik źródłowy')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('row_count', models.IntegerField(default=0)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partia wymiarów producenta',
                'verbose_name_plural': 'Partie wymiarów producenta',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProducerCartonDim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(db_index=True, max_length=120)),
                ('ref_code', models.CharField(db_index=True, max_length=100, verbose_name='REF')),
                ('carton_l', models.FloatField(blank=True, null=True, verbose_name='L kartonu [cm]')),
                ('carton_w', models.FloatField(blank=True, null=True, verbose_name='W kartonu [cm]')),
                ('carton_h', models.FloatField(blank=True, null=True, verbose_name='H kartonu [cm]')),
                ('qty_in_carton', models.IntegerField(blank=True, null=True)),
                ('gross_kg', models.FloatField(blank=True, null=True)),
                ('net_kg', models.FloatField(blank=True, null=True)),
                ('box_size_raw', models.CharField(blank=True, max_length=120)),
                ('pouch_size_raw', models.CharField(blank=True, max_length=120)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='ui.producercartonbatch')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ui.product')),
            ],
            options={
                'verbose_name': 'Wymiar kartonu producenta',
                'verbose_name_plural': 'Wymiary kartonu producenta',
                'indexes': [models.Index(fields=['supplier', 'ref_code'], name='ui_producer_supplie_39f165_idx')],
            },
        ),
    ]
