# Generated by Django 5.2.16 on 2026-09-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0191_alter_importrun_kind_alter_task_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matnr', models.CharField(max_length=18, unique=True, verbose_name='MATNR (bez zer wiodących)')),
                ('ref', models.CharField(blank=True, db_index=True, default='', max_length=60, verbose_name='REF')),
                ('name', models.CharField(blank=True, default='', max_length=250, verbose_name='Nazwa')),
                ('kind', models.CharField(blank=True, default='', max_length=4, verbose_name='Rodzaj materiału')),
                ('hierarchy', models.CharField(blank=True, db_index=True, default='', max_length=18, verbose_name='Hierarchia (kod)')),
                ('h1', models.CharField(blank=True, default='', max_length=120, verbose_name='H1 — asortyment')),
                ('h2', models.CharField(blank=True, default='', max_length=120, verbose_name='H2')),
                ('h3', models.CharField(blank=True, default='', max_length=120, verbose_name='H3')),
                ('h4', models.CharField(blank=True, default='', max_length=120, verbose_name='H4')),
                ('producer', models.CharField(blank=True, default='', max_length=120, verbose_name='Producent')),
                ('cn_code', models.CharField(blank=True, default='', max_length=12, verbose_name='Kod CN')),
                ('purchase_group', models.CharField(blank=True, default='', max_length=10, verbose_name='Grupa zaopatrzeniowa')),
                ('base_unit', models.CharField(blank=True, default='', max_length=6, verbose_name='JP')),
                ('pcs_per_opz', models.FloatField(blank=True, null=True, verbose_name='Sztuk w OPZ')),
                ('pcs_per_carton', models.FloatField(blank=True, null=True, verbose_name='Sztuk w kartonie')),
                ('pcs_per_pallet', models.FloatField(blank=True, null=True, verbose_name='Sztuk na palecie')),
                ('vol_unit_dm3', models.FloatField(blank=True, null=True, verbose_name='Objętość sztuki [dm³]')),
                ('vol_carton_dm3', models.FloatField(blank=True, null=True, verbose_name='Objętość kartonu [dm³]')),
                ('vol_pallet_dm3', models.FloatField(blank=True, null=True, verbose_name='Objętość palety [dm³]')),
                ('weight_unit_kg', models.FloatField(blank=True, null=True, verbose_name='Waga sztuki [kg]')),
                ('weight_carton_kg', models.FloatField(blank=True, null=True, verbose_name='Waga kartonu [kg]')),
                ('weight_pallet_kg', models.FloatField(blank=True, null=True, verbose_name='Waga palety [kg]')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dane materiałowe SAP',
                'verbose_name_plural': 'Dane materiałowe SAP',
                'ordering': ['matnr'],
            },
        ),
    ]
