# Generated by Django 5.2.16 on 2026-08-25 16:01

import django.db.models.deletion
from django.db import migrations, models


# W2 wydzielenia Magazynu 3D: przejęcie ISTNIEJĄCYCH tabel ui_* (db_table w modelach)
# — wyłącznie zmiana stanu, zero SQL (SeparateDatabaseAndState).
class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=[
        migrations.CreateModel(
            name='PickerActivityBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa importu')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('row_count', models.IntegerField(default=0)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Partia aktywności pickerów',
                'db_table': 'ui_pickeractivitybatch',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Layout', max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('location_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ui_warehouselayout',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseLocationMasterBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('location_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ui_warehouselocationmasterbatch',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa modelu')),
                ('notes', models.TextField(blank=True, verbose_name='Uwagi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('floor_width_m', models.FloatField(default=50, verbose_name='Szerokość hali [m]')),
                ('floor_depth_m', models.FloatField(default=30, verbose_name='Głębokość hali [m]')),
            ],
            options={
                'verbose_name': 'Model magazynu',
                'verbose_name_plural': 'Modele magazynów',
                'db_table': 'ui_warehousemodel',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseRackType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Kod typu')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa')),
                ('kind', models.CharField(choices=[('rack', 'Regał'), ('zone', 'Strefa')], default='rack', max_length=8, verbose_name='Rodzaj')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='Opis (znaczenie kodu)')),
                ('width_mm', models.IntegerField(default=800, verbose_name='Szer. fiz. miejsca [mm]')),
                ('manip_mm', models.IntegerField(default=900, verbose_name='Szer. z manipulacją [mm]')),
                ('depth_mm', models.IntegerField(default=1100, verbose_name='Głębokość [mm]')),
                ('max_weight_kg', models.FloatField(default=1200, verbose_name='Max waga [kg]')),
                ('max_volume_m3', models.FloatField(default=2.5, verbose_name='Max objętość [m³]')),
                ('level_heights', models.JSONField(default=dict, verbose_name='Wysokości poziomów [mm]')),
                ('level_cols', models.JSONField(default=dict, help_text='np. {"1":1,"2":2,"3":1} — ile kolumn na każdym poziomie. Puste = 1 wszędzie.', verbose_name='Kolumny per poziom')),
                ('level_weights', models.JSONField(default=dict, help_text='np. {"1":1000,"2":300} — max waga na poziom (etykiety kg w widoku 3D).', verbose_name='Nośność poziomów [kg]')),
                ('color_hex', models.CharField(default='#f59e0b', max_length=7, verbose_name='Kolor 3D')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Typ regału (3D)',
                'verbose_name_plural': 'Typy regałów (3D)',
                'db_table': 'ui_warehouseracktype',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('row_count', models.IntegerField(default=0)),
                ('occupied_count', models.IntegerField(default=0)),
                ('blocked_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'ui_warehousesnapshot',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseSnapshotRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_code', models.CharField(db_index=True, max_length=50)),
                ('warehouse_type', models.CharField(blank=True, default='', max_length=10)),
                ('section', models.CharField(blank=True, default='', max_length=20)),
                ('storage_group', models.CharField(blank=True, default='', max_length=50)),
                ('is_empty', models.BooleanField(default=True)),
                ('blocked_pick', models.BooleanField(default=False)),
                ('blocked_put', models.BooleanField(default=False)),
                ('capacity_mm', models.IntegerField(default=0)),
                ('zone', models.CharField(blank=True, default='', max_length=10)),
                ('aisle', models.CharField(blank=True, default='', max_length=10)),
                ('stack', models.CharField(blank=True, default='', max_length=10)),
                ('col_code', models.CharField(blank=True, default='', max_length=5)),
                ('level', models.IntegerField(default=1)),
                ('col_idx', models.IntegerField(default=0)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='wh3d.warehousesnapshot')),
            ],
            options={
                'db_table': 'ui_warehousesnapshotrow',
                'ordering': ['location_code', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PickerActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_code', models.CharField(db_index=True, max_length=50)),
                ('confirmed_at', models.DateTimeField(db_index=True)),
                ('picker_name', models.CharField(blank=True, default='', max_length=100)),
                ('task_type', models.CharField(blank=True, default='', max_length=50)),
                ('material_code', models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='Materiał / indeks')),
                ('qty', models.FloatField(blank=True, null=True, verbose_name='Ilość')),
                ('unit', models.CharField(blank=True, default='', max_length=20, verbose_name='JM')),
                ('lot', models.CharField(blank=True, default='', max_length=32, verbose_name='Partia / seria')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='wh3d.pickeractivitybatch')),
            ],
            options={
                'db_table': 'ui_pickeractivity',
                'indexes': [models.Index(fields=['batch', 'confirmed_at'], name='ui_pickerac_batch_i_2e2de0_idx'), models.Index(fields=['batch', 'location_code'], name='ui_pickerac_batch_i_abdb41_idx'), models.Index(fields=['material_code', 'lot'], name='ui_pickerac_materia_062862_idx')],
            },
        ),
        migrations.CreateModel(
            name='WarehouseAisleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aisle', models.CharField(max_length=30, verbose_name='Aleja')),
                ('width_m', models.FloatField(default=2.0, verbose_name='Szerokość korytarza [m]')),
                ('angle_deg', models.FloatField(default=0, verbose_name='Kąt obrotu [°]')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Uwagi')),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aisles', to='wh3d.warehouselayout')),
            ],
            options={
                'verbose_name': 'Konfiguracja alei',
                'verbose_name_plural': 'Konfiguracje alej',
                'db_table': 'ui_warehouseaisleconfig',
                'ordering': ['aisle'],
                'unique_together': {('layout', 'aisle')},
            },
        ),
        migrations.CreateModel(
            name='WarehouseLayoutCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_code', models.CharField(db_index=True, max_length=50)),
                ('grid_row', models.IntegerField()),
                ('grid_col', models.IntegerField()),
                ('level', models.IntegerField(default=1)),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='wh3d.warehouselayout')),
            ],
            options={
                'db_table': 'ui_warehouselayoutcell',
                'ordering': ['layout', 'id'],
                'indexes': [models.Index(fields=['layout', 'grid_row', 'grid_col'], name='ui_warehous_layout__726606_idx')],
                'unique_together': {('layout', 'location_code')},
            },
        ),
        migrations.CreateModel(
            name='WarehouseLocationMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_code', models.CharField(db_index=True, max_length=50)),
                ('level', models.IntegerField(default=1)),
                ('warehouse_type', models.CharField(blank=True, default='', max_length=50)),
                ('height_mm', models.IntegerField(default=0)),
                ('width_mm', models.IntegerField(default=0)),
                ('depth_mm', models.IntegerField(default=0)),
                ('max_volume_m3', models.FloatField(default=0.0)),
                ('max_weight_kg', models.FloatField(default=0.0)),
                ('blocked_pick', models.BooleanField(default=False, verbose_name='Blokada wydania')),
                ('blocked_put', models.BooleanField(default=False, verbose_name='Blokada umieszczania')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='wh3d.warehouselocationmasterbatch')),
            ],
            options={
                'db_table': 'ui_warehouselocationmaster',
                'ordering': ['location_code', 'id'],
                'unique_together': {('batch', 'location_code')},
            },
        ),
        migrations.CreateModel(
            name='WarehouseHallFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('dock', 'Dok przeładunkowy'), ('gate', 'Brama'), ('corridor', 'Korytarz / ciąg komunikacyjny'), ('block_zone', 'Strefa blokowa / nietypowa'), ('returns', 'Strefa zwrotów'), ('leader', 'Stanowisko lidera'), ('station', 'Stanowisko / punkt kontroli'), ('other', 'Inny obszar')], default='other', max_length=20, verbose_name='Typ elementu')),
                ('label', models.CharField(blank=True, max_length=100, verbose_name='Etykieta')),
                ('zone_code', models.CharField(blank=True, help_text='Dla stref blokowych/zwrotów — łapie kody po prefiksie', max_length=20, verbose_name='Prefiks kodów lokalizacji')),
                ('x_m', models.FloatField(default=0, verbose_name='Pozycja X [m]')),
                ('y_m', models.FloatField(default=0, verbose_name='Pozycja Y [m]')),
                ('width_m', models.FloatField(default=2, verbose_name='Szerokość [m]')),
                ('depth_m', models.FloatField(default=2, verbose_name='Głębokość [m]')),
                ('angle_deg', models.FloatField(default=0, verbose_name='Kąt obrotu [°]')),
                ('color_hex', models.CharField(blank=True, max_length=7, verbose_name='Kolor')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Uwagi')),
                ('layout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='wh3d.warehouselayout')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='wh3d.warehousemodel')),
            ],
            options={
                'verbose_name': 'Element hali',
                'verbose_name_plural': 'Elementy hali',
                'db_table': 'ui_warehousehallfeature',
                'ordering': ['kind', 'label'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('layout__isnull', True), ('model__isnull', False)), models.Q(('layout__isnull', False), ('model__isnull', True)), _connector='OR'), name='hallfeature_one_owner')],
            },
        ),
        migrations.CreateModel(
            name='WarehouseModelRack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(db_index=True, max_length=20, verbose_name='Strefa')),
                ('rack_id', models.CharField(max_length=20, verbose_name='Nr regału')),
                ('n_bays', models.IntegerField(default=1, verbose_name='Liczba boków (bays)')),
                ('n_levels', models.IntegerField(default=3, verbose_name='Liczba poziomów')),
                ('bay_width_cm', models.IntegerField(default=100, verbose_name='Szerokość boku [cm]')),
                ('depth_cm', models.IntegerField(default=80, verbose_name='Głębokość regału [cm]')),
                ('level_height_cm', models.IntegerField(default=200, verbose_name='Wys. poziomów [cm]')),
                ('x_m', models.FloatField(blank=True, null=True, verbose_name='Pozycja X [m]')),
                ('y_m', models.FloatField(blank=True, null=True, verbose_name='Pozycja Y [m]')),
                ('angle_deg', models.FloatField(default=0, verbose_name='Kąt obrotu [°]')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='wh3d.warehousemodel')),
            ],
            options={
                'verbose_name': 'Regał modelu',
                'verbose_name_plural': 'Regały modelu',
                'db_table': 'ui_warehousemodelrack',
                'ordering': ['zone', 'rack_id'],
                'unique_together': {('model', 'zone', 'rack_id')},
            },
        )
        ]),
    ]
