# Generated by Django 5.2.16 on 2026-09-25 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wh3d", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WarehouseDesignVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nazwa wariantu"),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("blender", "Blender (zestaw projektowy)"),
                            ("model", "Model magazynu"),
                        ],
                        default="blender",
                        max_length=10,
                        verbose_name="Źródło",
                    ),
                ),
                (
                    "floor_width_m",
                    models.FloatField(default=50, verbose_name="Szerokość hali [m]"),
                ),
                (
                    "floor_depth_m",
                    models.FloatField(default=30, verbose_name="Głębokość hali [m]"),
                ),
                ("elements", models.JSONField(default=list, verbose_name="Elementy")),
                (
                    "features",
                    models.JSONField(
                        default=list, verbose_name="Elementy hali (doki, strefy)"
                    ),
                ),
                ("kpi", models.JSONField(default=dict, verbose_name="Wskaźniki")),
                ("notes", models.TextField(blank=True, verbose_name="Uwagi")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "base_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="design_variants",
                        to="wh3d.warehousemodel",
                        verbose_name="Model bazowy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wariant projektu magazynu",
                "verbose_name_plural": "Warianty projektu magazynu",
                "ordering": ["-created_at"],
            },
        ),
    ]
