# Generated by Django 5.2.16 on 2026-09-25 17:26

import django.db.models.deletion
import wh3d.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wh3d', '0002_design_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='BayTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa')),
                ('beam_mm', models.IntegerField(default=2700, verbose_name='Szerokość belki [mm]')),
                ('pallets_per_beam', models.PositiveSmallIntegerField(default=3, verbose_name='Palet na belce')),
                ('depth_mm', models.IntegerField(default=1100, verbose_name='Głębokość [mm]')),
                ('levels', models.JSONField(blank=True, default=list, verbose_name='Poziomy (od dołu)')),
                ('notes', models.CharField(blank=True, default='', max_length=200, verbose_name='Uwagi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Szablon gniazda',
                'verbose_name_plural': 'Szablony gniazd',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='warehousemodelrack',
            name='bay_numbers',
            field=models.CharField(blank=True, default='', help_text='Zakresy, np. 10-47,50. Puste = 1…liczba gniazd.', max_length=200, validators=[wh3d.models.validate_bay_numbers], verbose_name='Numeracja gniazd'),
        ),
        migrations.AddField(
            model_name='warehousemodelrack',
            name='reverse',
            field=models.BooleanField(default=False, verbose_name='Numeracja od końca rzędu'),
        ),
        migrations.AddField(
            model_name='warehousemodelrack',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='racks', to='wh3d.baytemplate', verbose_name='Szablon gniazda'),
        ),
        migrations.CreateModel(
            name='LocationOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bay', models.IntegerField(verbose_name='Gniazdo (numer z adresu)')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Pozycja palety')),
                ('letter', models.CharField(blank=True, default='', max_length=1, verbose_name='Litera poziomu')),
                ('half', models.PositiveSmallIntegerField(default=0, verbose_name='Połówka (0/1/2)')),
                ('action', models.CharField(choices=[('template', 'Inny szablon gniazda'), ('skip', 'Pomiń'), ('add', 'Dodaj miejsce'), ('rename', 'Własny adres'), ('ewm_type', 'Inny typ EWM'), ('split', 'Podziel na połówki'), ('unsplit', 'Scal połówki'), ('block', 'Blokada')], max_length=10, verbose_name='Wyjątek')),
                ('value', models.CharField(blank=True, default='', max_length=50, verbose_name='Wartość (kod / typ EWM)')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='wh3d.warehousemodelrack')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bay_overrides', to='wh3d.baytemplate', verbose_name='Szablon (dla wyjątku gniazda)')),
            ],
            options={
                'verbose_name': 'Wyjątek adresu',
                'verbose_name_plural': 'Wyjątki adresów',
                'ordering': ['rack', 'bay', 'letter', 'position', 'half'],
                'constraints': [models.UniqueConstraint(fields=('rack', 'bay', 'position', 'letter', 'half', 'action'), name='locationoverride_unique')],
            },
        ),
    ]
