# Generated by Django 5.2.16 on 2026-09-26 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wh3d', '0003_baytemplate_warehousemodelrack_bay_numbers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseTaskBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa importu')),
                ('file_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Plik')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('queued', 'W kolejce'), ('running', 'Import trwa'), ('done', 'Zaimportowano'), ('error', 'Błąd')], default='queued', max_length=10)),
                ('message', models.TextField(blank=True, default='', verbose_name='Komunikat')),
                ('tz', models.CharField(choices=[('Europe/Warsaw', 'Czas lokalny (Europe/Warsaw)'), ('UTC', 'UTC')], default='Europe/Warsaw', max_length=40, verbose_name='Strefa czasowa pliku')),
                ('kind_map', models.JSONField(blank=True, default=dict, verbose_name='Nadpisania mapowania (proces → rodzaj)')),
                ('row_count', models.IntegerField(default=0, verbose_name='Zadań')),
                ('error_count', models.IntegerField(default=0, verbose_name='Błędnych wierszy')),
                ('first_confirmed', models.DateTimeField(blank=True, null=True)),
                ('last_confirmed', models.DateTimeField(blank=True, null=True)),
                ('stats', models.JSONField(blank=True, default=dict, verbose_name='Statystyki')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Import zadań magazynowych EWM',
                'verbose_name_plural': 'Importy zadań magazynowych EWM',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_no', models.CharField(blank=True, default='', max_length=20, verbose_name='Nr WT')),
                ('process_type', models.CharField(blank=True, default='', max_length=10, verbose_name='Rodzaj procesu mag.')),
                ('kind', models.CharField(choices=[('putaway', 'Przyjęcie / odłożenie'), ('replenishment', 'Uzupełnienie'), ('picking', 'Kompletacja'), ('outbound', 'Wydanie / załadunek'), ('move', 'Przesunięcie')], default='move', max_length=14, verbose_name='Rodzaj ruchu')),
                ('src_location', models.CharField(blank=True, default='', max_length=50, verbose_name='Lokalizacja źródłowa')),
                ('dst_location', models.CharField(blank=True, default='', max_length=50, verbose_name='Lokalizacja docelowa')),
                ('material', models.CharField(blank=True, default='', max_length=50, verbose_name='Materiał')),
                ('lot', models.CharField(blank=True, default='', max_length=32, verbose_name='Partia')),
                ('qty', models.FloatField(blank=True, null=True, verbose_name='Ilość')),
                ('unit', models.CharField(blank=True, default='', max_length=10, verbose_name='JM')),
                ('src_hu', models.CharField(blank=True, default='', max_length=40, verbose_name='HU źródłowa')),
                ('dst_hu', models.CharField(blank=True, default='', max_length=40, verbose_name='HU docelowa')),
                ('document', models.CharField(blank=True, default='', max_length=35, verbose_name='Dokument')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Utworzono')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Potwierdzono')),
                ('user', models.CharField(blank=True, default='', max_length=40, verbose_name='Użytkownik')),
                ('resource', models.CharField(blank=True, default='', max_length=40, verbose_name='Zasób')),
                ('queue', models.CharField(blank=True, default='', max_length=40, verbose_name='Kolejka')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='wh3d.warehousetaskbatch')),
            ],
            options={
                'verbose_name': 'Zadanie magazynowe EWM',
                'verbose_name_plural': 'Zadania magazynowe EWM',
                'indexes': [models.Index(fields=['batch', 'confirmed_at'], name='wh3d_wareho_batch_i_319c75_idx'), models.Index(fields=['batch', 'src_location'], name='wh3d_wareho_batch_i_ca9603_idx'), models.Index(fields=['batch', 'dst_location'], name='wh3d_wareho_batch_i_bf99f9_idx')],
            },
        ),
    ]
