# Generated by Django 5.2.16 on 2026-08-25 20:07

import django.core.validators
import django.db.models.deletion
import transport.models
from django.conf import settings
from django.db import migrations, models


# W2 wydzielenia Transportu: przejęcie ISTNIEJĄCYCH tabel ui_* (db_table w modelach)
# — wyłącznie zmiana stanu, zero SQL (SeparateDatabaseAndState).
class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ui', '0187_delete_controlledwarehousetype_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=[
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa przewoźnika')),
                ('carrier_type', models.CharField(choices=[('courier', 'Kurier (paczki)'), ('ltl', 'Drobnica LTL'), ('ftl', 'Całopojazdowy FTL')], default='ltl', max_length=20, verbose_name='Typ')),
                ('dim_weight_divisor', models.FloatField(default=5000, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Dzielnik wagi obj. [cm³/kg]')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('notes', models.TextField(blank=True, verbose_name='Uwagi')),
            ],
            options={
                'db_table': 'ui_carrier',
                'ordering': ['carrier_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QuoteRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nazwa / firma')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('is_warehouse', models.BooleanField(default=False, verbose_name='Magazyn')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Uwagi')),
            ],
            options={
                'db_table': 'ui_quoterecipient',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TransportKpiSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict, verbose_name='Dane KPI (kpi + charts)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ostatnie przeliczenie')),
            ],
            options={
                'verbose_name': 'Snapshot KPI transportu',
                'verbose_name_plural': 'Snapshot KPI transportu',
                'db_table': 'ui_transportkpisnapshot',
            },
        ),
        migrations.CreateModel(
            name='CarrierZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Strefa / kraj')),
                ('countries', models.CharField(blank=True, max_length=500, verbose_name='Kody krajów ISO (przecinek)')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='transport.carrier')),
            ],
            options={
                'db_table': 'ui_carrierzone',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CarrierRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_from_kg', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Waga od [kg]')),
                ('weight_to_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Waga do [kg] (puste = bez limitu)')),
                ('price_eur', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena [EUR]')),
                ('per_pallet_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Dopłata/paleta [EUR]')),
                ('fuel_surcharge_pct', models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='Dopłata paliwowa [%]')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Uwagi')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='transport.carrierzone')),
            ],
            options={
                'db_table': 'ui_carrierrate',
                'ordering': ['weight_from_kg'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa przesyłki')),
                ('destination_country', models.CharField(blank=True, max_length=2, verbose_name='Kraj docelowy (ISO)')),
                ('destination_city', models.CharField(blank=True, max_length=100, verbose_name='Miasto')),
                ('destination_postal', models.CharField(blank=True, max_length=20, verbose_name='Kod pocztowy')),
                ('recipient_name', models.CharField(blank=True, max_length=200, verbose_name='Odbiorca')),
                ('ramp', models.CharField(blank=True, max_length=20, verbose_name='Numer rampy')),
                ('wz_number', models.CharField(blank=True, max_length=40, verbose_name='Numer WZ')),
                ('kunnr', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Kod klienta SAP (KUNNR)')),
                ('outbound_delivery_date', models.DateField(blank=True, null=True, verbose_name='Data dostawy wychodzącej')),
                ('outbound_created_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Data utworzenia dostawy wychodzącej')),
                ('is_stock', models.BooleanField(db_index=True, default=False, verbose_name='Kontener stanu (import HU)')),
                ('picking_complete', models.BooleanField(db_index=True, default=False, verbose_name='Picking zakończony')),
                ('picking_complete_at', models.DateTimeField(blank=True, null=True)),
                ('picking_eta_note', models.CharField(blank=True, max_length=200, verbose_name='Status pickingu (ETA)')),
                ('picking_eta_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Robocze'), ('confirmed', 'Zatwierdzone'), ('sent', 'Wysłane'), ('cancelled', 'Anulowane')], default='draft', max_length=20, verbose_name='Status')),
                ('stowage_efficiency_pct', models.IntegerField(default=85, help_text='Realny stopień wykorzystania kubatury palety przy ręcznym układaniu (mieszane SKU nigdy nie pakują się w 100%). Niższa wartość → więcej palet.', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(100)], verbose_name='Efektywność układania [%]')),
                ('notes', models.TextField(blank=True, verbose_name='Uwagi')),
                ('client_requirements', models.CharField(blank=True, max_length=300, verbose_name='Wymagania klienta')),
                ('actual_hu_count', models.PositiveIntegerField(blank=True, help_text='Liczba jednostek obsługi z dokumentu dostawy SAP — faktyczna liczba palet, jaka wyszła. Gdy podana, wycena kotwiczy się na niej.', null=True, verbose_name='Rzeczywista liczba HU (SAP)')),
                ('warehouse_pallets', models.PositiveIntegerField(blank=True, help_text='Liczba palet uzgodniona z magazynem — kotwiczy wycenę i wysyłkę do spedycji.', null=True, verbose_name='Palet potwierdzonych przez magazyn')),
                ('transport_modes', models.CharField(blank=True, max_length=200, verbose_name='Typy wysyłki (pojazdy)')),
                ('anchor_note', models.CharField(blank=True, max_length=300, verbose_name='Komentarz do liczby palet (rozjazd danych)')),
                ('load_mode', models.CharField(choices=[('pallets', 'Na paletach'), ('loose', 'Bez palet (luzem)')], default='pallets', max_length=10, verbose_name='Tryb załadunku')),
                ('client_eta', models.DateField(blank=True, null=True, verbose_name='Przybliżona data dostawy do klienta')),
                ('client_loaded_notified_at', models.DateTimeField(blank=True, null=True, verbose_name='Powiadomiono klienta o załadunku')),
                ('ready_notified_at', models.DateTimeField(blank=True, null=True, verbose_name='Powiadomiono o gotowości wszystkich palet')),
                ('author', models.CharField(blank=True, max_length=120, verbose_name='Autor dostawy')),
                ('author_email', models.CharField(blank=True, max_length=200, verbose_name='E-mail autora')),
                ('selected_pallet_height_cm', models.IntegerField(blank=True, null=True, verbose_name='Wybrana wysokość palety [cm]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='ui.customer', verbose_name='Klient / odbiorca')),
                ('picking_eta_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picking_eta_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ui_shipment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentQuoteOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier_name', models.CharField(blank=True, max_length=120, verbose_name='Spedycja')),
                ('token', models.CharField(db_index=True, default=transport.models._quote_token, max_length=32, unique=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Kwota')),
                ('currency', models.CharField(default='PLN', max_length=3, verbose_name='Waluta')),
                ('fuel_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Dopłata paliwowa [%]')),
                ('surcharge_fixed', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Dopłata stała')),
                ('surcharge_note', models.CharField(blank=True, max_length=200, verbose_name='Opis dopłat')),
                ('truck_date', models.DateField(blank=True, null=True, verbose_name='Podstawienie auta')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Data dostawy')),
                ('notes', models.CharField(blank=True, max_length=300, verbose_name='Uwagi spedycji')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='quotes/%Y/%m/', verbose_name='Załącznik (oferta/dokument)')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('selected', models.BooleanField(default=False, verbose_name='Wybrana')),
                ('sender_name', models.CharField(blank=True, max_length=120)),
                ('sender_email', models.CharField(blank=True, max_length=190)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.quoterecipient')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_offers', to='transport.shipment')),
            ],
            options={
                'db_table': 'ui_shipmentquoteoffer',
                'ordering': ['amount'],
                'unique_together': {('shipment', 'recipient')},
            },
        ),
        migrations.CreateModel(
            name='DriverAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_token', models.CharField(db_index=True, default=transport.models._quote_token, max_length=32, unique=True)),
                ('confirm_token', models.CharField(db_index=True, default=transport.models._quote_token, max_length=32, unique=True)),
                ('driver_name', models.CharField(blank=True, max_length=120, verbose_name='Kierowca')),
                ('driver_plate', models.CharField(blank=True, max_length=20, verbose_name='Nr auta')),
                ('driver_phone', models.CharField(blank=True, max_length=32, verbose_name='Telefon kierowcy')),
                ('driver_language', models.CharField(default='pl', max_length=20, verbose_name='Język komunikacji')),
                ('truck_eta', models.DateTimeField(blank=True, null=True, verbose_name='Szac. godz. podstawienia auta')),
                ('filled_at', models.DateTimeField(blank=True, null=True)),
                ('pickup_status', models.CharField(choices=[('pending', 'Oczekuje'), ('confirmed', 'Potwierdzony'), ('declined', 'Odmowa')], default='pending', max_length=10)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('sms_count', models.PositiveIntegerField(default=0)),
                ('sms_last_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='transport.shipment')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.shipmentquoteoffer')),
            ],
            options={
                'db_table': 'ui_driverassignment',
            },
        ),
        migrations.CreateModel(
            name='ShipmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(blank=True, default='', max_length=50, verbose_name='Kod produktu')),
                ('quantity', models.FloatField(verbose_name='Ilość')),
                ('unit', models.CharField(choices=[('szt', 'Sztuki (szt)'), ('kar', 'Kartony (KAR)'), ('pal', 'Palety')], default='kar', max_length=10, verbose_name='Jednostka')),
                ('source_unit', models.CharField(blank=True, max_length=20, verbose_name='Jedn. źródłowa')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Uwagi')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ui.product', verbose_name='Produkt')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='transport.shipment')),
            ],
            options={
                'db_table': 'ui_shipmentline',
                'ordering': ['order', 'id'],
                'unique_together': {('shipment', 'product')},
            },
        ),
        migrations.CreateModel(
            name='WarehouseReadiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('pre', 'Gotowość wstępna (15 min)'), ('date', 'Gotowość na datę odbioru')], max_length=8)),
                ('token', models.CharField(db_index=True, default=transport.models._quote_token, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Oczekuje'), ('yes', 'Potwierdzone'), ('no', 'Odmowa')], default='pending', max_length=8)),
                ('pickup_date', models.DateField(blank=True, null=True, verbose_name='Data odbioru')),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('asked_pallets', models.PositiveIntegerField(blank=True, null=True, verbose_name='Palet w zapytaniu')),
                ('confirmed_pallets', models.PositiveIntegerField(blank=True, null=True, verbose_name='Palet potwierdzonych')),
                ('suggested_pallets', models.PositiveIntegerField(blank=True, null=True, verbose_name='Palet proponowanych przez magazyn')),
                ('ready_at', models.DateTimeField(blank=True, null=True, verbose_name='Najszybszy termin gotowości')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wh_confirmations', to='transport.shipment')),
            ],
            options={
                'db_table': 'ui_warehousereadiness',
                'ordering': ['kind'],
                'unique_together': {('shipment', 'kind')},
            },
        ),
        ]),
    ]
