# Generated by Django 5.2.16 on 2026-09-28 00:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
        ('ui', '0192_material_master'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['name', 'is_stock'], name='shipment_name_stock_idx'),
        ),
    ]
