from django.urls import path
from . import views as huctl_views

# Included WITHOUT a prefix from ui/urls.py (path("", include("huctl.urls"))).
# No app_name: names merge into namespace ui: — reverse("ui:<name>") unchanged.

urlpatterns = [
    path("planner/shipments/<int:pk>/generate-hus/", huctl_views.planner_shipment_generate_hus, name="planner_shipment_generate_hus"),
    path("planner/hu-import/", huctl_views.planner_hu_import, name="planner_hu_import"),

    # ── Warehouse stock (imported HU) — own tab, shared by control + 3D map ──────
    path("stock-warehouse/", huctl_views.planner_stock, name="planner_stock"),
    path("stock-warehouse/contents/", huctl_views.planner_stock_contents, name="planner_stock_contents"),
    path("stock-warehouse/powerbi/", huctl_views.planner_stock_powerbi_import, name="planner_stock_powerbi_import"),
    path("stock-warehouse/powerbi/connect/", huctl_views.planner_stock_powerbi_connect, name="planner_stock_powerbi_connect"),
    path("stock-warehouse/powerbi/status/", huctl_views.planner_stock_powerbi_status, name="planner_stock_powerbi_status"),

    # ── HU control (scanner transaction) ────────────────────────────────────────
    path("control-hub/", huctl_views.hu_control_hub, name="hu_control_hub"),
    path("control/leader/", huctl_views.hu_control_leader, name="hu_control_leader"),
    path("control/leader/message/", huctl_views.hu_control_message, name="hu_control_message"),
    path("control/leader/photo-task/", huctl_views.hu_control_photo_task, name="hu_control_photo_task"),
    path("control/hu/<int:pk>/assign/", huctl_views.hu_control_assign, name="hu_control_assign"),
    path("control/hu/<int:pk>/assign-group/", huctl_views.hu_control_assign_group, name="hu_control_assign_group"),
    path("control/hu/<int:pk>/label/", huctl_views.hu_logistics_label, name="hu_logistics_label"),
    # Fala 4: wyjątki master daty per pozycja
    path("control/item/<int:item_id>/md-exception/", huctl_views.hu_item_md_exception,
         name="hu_item_md_exception"),
    path("control/item/<int:item_id>/md-report/", huctl_views.hu_md_report, name="hu_md_report"),
    path("control/item/<int:item_id>/md-exception/close/", huctl_views.hu_item_md_exception_close,
         name="hu_item_md_exception_close"),
    path("control/item/<int:item_id>/md-exception/delete/", huctl_views.hu_item_md_exception_delete,
         name="hu_item_md_exception_delete"),
    path("control-hub/tv/", huctl_views.hu_control_tv, name="hu_control_tv"),
    path("control-hub/types/", huctl_views.hu_control_types, name="hu_control_types"),
    path("control/", huctl_views.hu_control_menu, name="hu_control_menu"),
    path("control/zone/", huctl_views.hu_zone_select, name="hu_zone_select"),
    path("control/my/", huctl_views.hu_my_shift, name="hu_my_shift"),
    path("control/my/next/", huctl_views.hu_take_next, name="hu_take_next"),
    path("control/hu/<int:pk>/investigate/", huctl_views.hu_investigation_start, name="hu_investigation_start"),
    path("control/investigation/<int:pk>/", huctl_views.hu_investigation_detail, name="hu_investigation_detail"),
    path("control/investigation/<int:pk>/end/", huctl_views.hu_investigation_end, name="hu_investigation_end"),
    path("control/investigation/<int:pk>/confirm/", huctl_views.hu_investigation_confirm, name="hu_investigation_confirm"),
    path("control/investigation/<int:pk>/reject/", huctl_views.hu_investigation_reject, name="hu_investigation_reject"),
    path("control/scan/", huctl_views.hu_control_scan, name="hu_control_scan"),
    path("control/recipient/", huctl_views.hu_control_find_recipient, name="hu_control_find_recipient"),
    path("control/next/", huctl_views.hu_control_next, name="hu_control_next"),
    path("control/hu/<int:pk>/zdjecie/", huctl_views.hu_photo_check, name="hu_photo_check"),
    path("control/hu/<int:pk>/", huctl_views.hu_control_detail, name="hu_control_detail"),
    path("control/hu/<int:pk>/przynies/", huctl_views.hu_request_bring, name="hu_request_bring"),
    path("control/hu/<int:pk>/wywolaj/", huctl_views.hu_call, name="hu_call"),
    path("control/hu/<int:pk>/przejmij-rezerwacje/", huctl_views.hu_reserve_takeover, name="hu_reserve_takeover"),
    path("control/hu/<int:pk>/przypisz-grupe/", huctl_views.hu_reserve_group, name="hu_reserve_group"),
    path("control/hu/wywolaj-wsad/", huctl_views.hu_call_batch, name="hu_call_batch"),
    path("control/hu/wywolaj-zaznaczone/", huctl_views.hu_call_selected, name="hu_call_selected"),
    path("control/eskaluj/", huctl_views.hu_escalate, name="hu_escalate"),
    path("shipments/<int:pk>/eta-note/", huctl_views.shipment_eta_note, name="shipment_eta_note"),
    path("control/hu/<int:pk>/zwolnij/", huctl_views.hu_release, name="hu_release"),
    path("control/hu/<int:pk>/pilne/", huctl_views.hu_urgent_pull, name="hu_urgent_pull"),
    path("control/hu/<int:pk>/start/", huctl_views.hu_control_start, name="hu_control_start"),
    path("control/hu/<int:pk>/disposition/", huctl_views.hu_control_disposition, name="hu_control_disposition"),
    path("control/hu/<int:pk>/history/", huctl_views.hu_control_history, name="hu_control_history"),
    path("control/hu/<int:pk>/takeover/", huctl_views.hu_control_takeover, name="hu_control_takeover"),
    path("control/hu/<int:pk>/confirm-reqs/", huctl_views.hu_control_confirm_reqs, name="hu_control_confirm_reqs"),
    path("control/hu/<int:pk>/ack-short-dated/", huctl_views.hu_control_ack_short_dated, name="hu_control_ack_short_dated"),
    path("control/hu/<int:pk>/foreign/", huctl_views.hu_quality_add_foreign, name="hu_quality_add_foreign"),
    path("control/prod-codes/", huctl_views.hu_prod_codes, name="hu_prod_codes"),
    path("control/quality/", huctl_views.hu_quality_issues, name="hu_quality_issues"),
    path("control/quality/<int:issue_id>/close/", huctl_views.hu_quality_close, name="hu_quality_close"),
    path("control/quality/<int:issue_id>/photo/", huctl_views.hu_quality_attach, name="hu_quality_attach"),
    path("control/kpi/", huctl_views.hu_control_kpi, name="hu_control_kpi"),
    path("control/sync/", huctl_views.hu_control_sync, name="hu_control_sync"),
    path("control/hu/<int:pk>/reopen/", huctl_views.hu_control_reopen, name="hu_control_reopen"),
    path("control/hu/<int:pk>/item/<int:item_id>/", huctl_views.hu_control_count, name="hu_control_count"),
    path("control/hu/<int:pk>/finalize/", huctl_views.hu_control_finalize, name="hu_control_finalize"),
    path("control/notifications/", huctl_views.hu_notifications, name="hu_notifications"),
    path("control/gls-report/", huctl_views.gls_packing_report, name="gls_packing_report"),
    path("control/symulator/", huctl_views.scanner_simulator, name="scanner_simulator"),
    path("control/recheck/", huctl_views.hu_control_recheck_list, name="hu_control_recheck_list"),
    path("control/status/", huctl_views.hu_control_status, name="hu_control_status"),
    path("control/report/", huctl_views.hu_error_report, name="hu_error_report"),

    # ── Wydruk HU (etykiety ZPL — moduł „Magazyn") ──────────────────────────────
    path("hu-print/", huctl_views.hu_print_home, name="hu_print_home"),
    path("hu-print/generate/", huctl_views.hu_print_generate, name="hu_print_generate"),
    path("hu-print/preview/", huctl_views.hu_print_preview, name="hu_print_preview"),
    path("hu-print/log/", huctl_views.hu_print_log, name="hu_print_log"),
]
